#!/bin/bash
# --- MSP Worktree Safety Guard (Patch L, shared) ---
# shellcheck source=/dev/null
. "$(git rev-parse --show-toplevel 2>/dev/null)/Scripts/lib/worktree_guard.sh"
msp_enforce_main_repo_or_exit
# --- End MSP Worktree Safety Guard (Patch L, shared) ---
set -euo pipefail

# Generate a LOCAL development Package.swift that:
# - Uses Build/ReleaseArtifacts/XCFrameworks/* for MSP internal binaries
# - Uses Build/ReleaseArtifacts/XCFrameworks/<SDK>.xcframework for ad-network SDKs extracted from Pods
# - Uses SPM for UI libs like Kingfisher (SnapKit is provided as MSPSnapKit binary)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PKG_FILE="$ROOT_DIR/Package.swift"

log() { echo "[$(basename "$0")] $*"; }

log "Generating local-development Package.swift at $PKG_FILE"

cat > "$PKG_FILE" << 'SWIFT'
// swift-tools-version: 5.9
// This file is auto-generated by Scripts/spm-sync/generate_package_swift.sh
// Local development version: all ad network SDKs come from Build/ReleaseArtifacts/XCFrameworks.

import PackageDescription

let package = Package(
    name: "msp-ios-sdk",
    platforms: [
        .iOS(.v15),
        .macOS(.v10_15)
    ],
    products: [
        .library(name: "MSPAds", targets: ["MSPCore", "MSPSharedLibraries", "MSPiOSCore"]),
        .library(name: "MSPCore", targets: ["MSPCore"]),
        .library(name: "MSPSharedLibraries", targets: ["MSPSharedLibraries"]),
        .library(name: "MSPiOSCore", targets: ["MSPiOSCore"]),
        .library(name: "NovaCore", targets: ["NovaCore"]),
        .library(name: "MSPOMSDK", targets: ["MSPOMSDK"]),
        .library(name: "MSPGoogleAdsTypes", targets: ["MSPGoogleAdsTypes"]),
        .library(name: "MSPPrebidAdapter", targets: ["MSPPrebidAdapter"]),
        .library(name: "MSPGoogleAdapter", targets: ["MSPGoogleAdapter"]),
        .library(name: "MSPFacebookAdapter", targets: ["MSPFacebookAdapter"]),
        .library(name: "NovaAdapter", targets: ["NovaAdapter"]),
        .library(name: "MSPAmazonAdapter", targets: ["MSPAmazonAdapter"]),
        .library(name: "MSPMolocoAdapter", targets: ["MSPMolocoAdapter"]),
        .library(name: "MSPLiftoffAdapter", targets: ["MSPLiftoffAdapter"]),
        .library(name: "UnityAdapter", targets: ["UnityAdapter"]),
        .library(name: "InmobiAdapter", targets: ["InmobiAdapter"]),
        .library(name: "MobilefuseAdapter", targets: ["MobilefuseAdapter"]),
        .library(name: "MintegralAdapter", targets: ["MintegralAdapter"]),
        .library(name: "PubmaticAdapter", targets: ["PubmaticAdapter"]),
    ],
    dependencies: [
        // Google Mobile Ads SDK - Required by MSPGoogleAdsTypes
        .package(url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git", from: "11.0.0"),
        // UI / utility libraries that are cleanly supported via SPM
        .package(url: "https://github.com/onevcat/Kingfisher.git", from: "8.6.2"),
    ],
    targets: [

        // MARK: - Core binary XCFrameworks (built by your internal build.sh)
        .binaryTarget(
            name: "MSPSharedLibraries",
            path: "Build/ReleaseArtifacts/XCFrameworks/MSPSharedLibraries.xcframework"
        ),
        .binaryTarget(
            name: "MSPiOSCore",
            path: "Build/ReleaseArtifacts/XCFrameworks/MSPiOSCore.xcframework"
        ),
        .binaryTarget(
            name: "NovaCore",
            path: "Build/ReleaseArtifacts/XCFrameworks/NovaCore.xcframework"
        ),
        .binaryTarget(
            name: "MSPCore",
            path: "Build/ReleaseArtifacts/XCFrameworks/MSPCore.xcframework"
        ),
        .binaryTarget(
            name: "MSPOMSDK",
            path: "Build/ReleaseArtifacts/XCFrameworks/MSPOMSDK.xcframework"
        ),

        // MARK: - Third-party SDK binary XCFrameworks extracted from Pods

        .binaryTarget(
            name: "PrebidMobile",
            path: "Build/ReleaseArtifacts/XCFrameworks/PrebidMobile.xcframework"
        ),
        .binaryTarget(
            name: "MSPSnapKit",
            path: "Build/ReleaseArtifacts/XCFrameworks/MSPSnapKit.xcframework"
        ),
        .binaryTarget(
            name: "MolocoSDKiOS",
            path: "Build/ReleaseArtifacts/XCFrameworks/MolocoSDKiOS.xcframework"
        ),
        .binaryTarget(
            name: "VungleAds",
            path: "Build/ReleaseArtifacts/XCFrameworks/VungleAds.xcframework"
        ),
        // GoogleMobileAds is now provided via SPM package (swift-package-manager-google-mobile-ads)
        .binaryTarget(
            name: "FBAudienceNetwork",
            path: "Build/ReleaseArtifacts/XCFrameworks/FBAudienceNetwork.xcframework"
        ),
        .binaryTarget(
            name: "IronSourceSDK",
            path: "Build/ReleaseArtifacts/XCFrameworks/IronSourceSDK.xcframework"
        ),
        .binaryTarget(
            name: "InMobiSDK",
            path: "Build/ReleaseArtifacts/XCFrameworks/InMobiSDK.xcframework"
        ),
        .binaryTarget(
            name: "MobileFuseSDK",
            path: "Build/ReleaseArtifacts/XCFrameworks/MobileFuseSDK.xcframework"
        ),
        .binaryTarget(
            name: "OpenWrapSDK",
            path: "Build/ReleaseArtifacts/XCFrameworks/OpenWrapSDK.xcframework"
        ),
        .binaryTarget(
            name: "AmazonPublisherServicesSDK",
            path: "Build/ReleaseArtifacts/XCFrameworks/AmazonPublisherServicesSDK.xcframework"
        ),

        // MARK: - Shared modules (abstraction layers)
        
        .target(
            name: "MSPGoogleAdsTypes",
            dependencies: [
                .product(name: "GoogleMobileAds", package: "swift-package-manager-google-mobile-ads"),
            ],
            path: "Sources/Common/MSPGoogleAdsTypes"
        ),

        // MARK: - Adapter source targets (10)

        .target(
            name: "MSPPrebidAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "PrebidMobile"
            ],
            path: "Sources/Adapters/MSPPrebidAdapter/MSPPrebidAdapter"
        ),
        .target(
            name: "MSPGoogleAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "MSPGoogleAdsTypes"
            ],
            path: "Sources/Adapters/MSPGoogleAdapter/MSPGoogleAdapter"
        ),
        .target(
            name: "MSPFacebookAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "FBAudienceNetwork"
            ],
            path: "Sources/Adapters/MSPFacebookAdapter/MSPFacebookAdapter"
        ),
        .target(
            name: "NovaAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "NovaCore",
                "MSPOMSDK",
                .product(name: "Kingfisher", package: "Kingfisher"),
                "MSPSnapKit"
            ],
            path: "Sources/Adapters/NovaAdapter/NovaAdapter"
        ),
        .target(
            name: "MSPAmazonAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "MSPGoogleAdsTypes",
                "AmazonPublisherServicesSDK"
            ],
            path: "Sources/Adapters/AmazonAdapter/AmazonAdapter"
        ),
        .target(
            name: "MSPMolocoAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "MolocoSDKiOS",
                "MSPSnapKit"
            ],
            path: "Sources/Adapters/MolocoAdapter/MolocoAdapter"
        ),
        .target(
            name: "MSPLiftoffAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "VungleAds",
                "MSPSnapKit"
            ],
            path: "Sources/Adapters/LiftoffAdapter/LiftoffAdapter"
        ),
        .target(
            name: "UnityAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "IronSourceSDK"
            ],
            path: "Sources/Adapters/UnityAdapter/UnityAdapter"
        ),
        .target(
            name: "InmobiAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "InMobiSDK"
            ],
            path: "Sources/Adapters/InmobiAdapter/InmobiAdapter"
        ),
        .target(
            name: "MobilefuseAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "MobileFuseSDK"
            ],
            path: "Sources/Adapters/MobilefuseAdapter/MobilefuseAdapter"
        ),
        .target(
            name: "MintegralAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
            ],
            path: "Sources/Adapters/MintegralAdapter/MintegralAdapter"
        ),
        .target(
            name: "PubmaticAdapter",
            dependencies: [
                "MSPSharedLibraries",
                "MSPiOSCore",
                "OpenWrapSDK"
            ],
            path: "Sources/Adapters/PubmaticAdapter/PubmaticAdapter"
        ),
    ]
)
SWIFT

log "✅ Package.swift generated."
