#!/usr/bin/env bash
# --- MSP Worktree Safety Guard (Patch M, shared) ---
# shellcheck source=/dev/null
_msp_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$_msp_root" ] && [ -f "$_msp_root/Scripts/lib/worktree_guard.sh" ]; then
  . "$_msp_root/Scripts/lib/worktree_guard.sh"
  msp_enforce_main_repo_or_exit
fi
unset _msp_root
# --- End MSP Worktree Safety Guard (Patch M, shared) ---
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=Scripts/lib/paths.sh
source "$ROOT_DIR/Scripts/lib/paths.sh"

# R029e: Source xcodegen module for unified generation
if [[ -f "$ROOT_DIR/Scripts/lib/xcodegen.sh" ]]; then
    # shellcheck source=Scripts/lib/xcodegen.sh
    source "$ROOT_DIR/Scripts/lib/xcodegen.sh" 2>/dev/null || true
fi

init_paths
# shellcheck source=Scripts/lib/demoapp_config.sh
source "$ROOT_DIR/Scripts/lib/demoapp_config.sh"
demoapp_load_config || true
DEMOAPP_DIR=""
DEMOAPP_REL=""
if [[ -d "$ROOT_DIR/Examples/MSPDemoApp/MSPDemoApp" ]]; then
  DEMOAPP_DIR="$ROOT_DIR/Examples/MSPDemoApp"
  DEMOAPP_REL="Examples/MSPDemoApp"
  DEMOAPP_PODS_XCCONFIG_DEBUG_REL="$DEMOAPP_PODS_XCCONFIG_DEBUG_REL_EXAMPLES"
  DEMOAPP_PODS_XCCONFIG_RELEASE_REL="$DEMOAPP_PODS_XCCONFIG_RELEASE_REL_EXAMPLES"
  PODS_ROOT_REL='$(SRCROOT)/../../Pods'
elif [[ -d "$ROOT_DIR/MSPDemoApp/MSPDemoApp" ]]; then
  DEMOAPP_DIR="$ROOT_DIR/MSPDemoApp"
  DEMOAPP_REL="MSPDemoApp"
  DEMOAPP_PODS_XCCONFIG_DEBUG_REL="$DEMOAPP_PODS_XCCONFIG_DEBUG_REL_ROOT"
  DEMOAPP_PODS_XCCONFIG_RELEASE_REL="$DEMOAPP_PODS_XCCONFIG_RELEASE_REL_ROOT"
  PODS_ROOT_REL='$(SRCROOT)/../Pods'
elif [[ -d "$ROOT_DIR/Examples/MSPDemoApp" ]]; then
  DEMOAPP_DIR="$ROOT_DIR/Examples/MSPDemoApp"
  DEMOAPP_REL="Examples/MSPDemoApp"
  DEMOAPP_PODS_XCCONFIG_DEBUG_REL="$DEMOAPP_PODS_XCCONFIG_DEBUG_REL_EXAMPLES"
  DEMOAPP_PODS_XCCONFIG_RELEASE_REL="$DEMOAPP_PODS_XCCONFIG_RELEASE_REL_EXAMPLES"
  PODS_ROOT_REL='$(SRCROOT)/../../Pods'
else
  DEMOAPP_DIR="$ROOT_DIR/MSPDemoApp"
  DEMOAPP_REL="MSPDemoApp"
  DEMOAPP_PODS_XCCONFIG_DEBUG_REL="$DEMOAPP_PODS_XCCONFIG_DEBUG_REL_ROOT"
  DEMOAPP_PODS_XCCONFIG_RELEASE_REL="$DEMOAPP_PODS_XCCONFIG_RELEASE_REL_ROOT"
  PODS_ROOT_REL='$(SRCROOT)/../Pods'
fi

PROJECT_SPEC="$DEMOAPP_DIR/project.yml"
WORKSPACE_SPEC="$ROOT_DIR/workspace.yml"
WORKSPACE_PATH="$ROOT_DIR/msp-ios-sdk.xcworkspace"
WORKSPACE_DATA="$WORKSPACE_PATH/contents.xcworkspacedata"
SWIFTPM_DIR="$WORKSPACE_PATH/xcshareddata/swiftpm"
SWIFTPM_JSON="$SWIFTPM_DIR/local-packages.json"
LOG_PREFIX="[update-workspace]"
DEMOAPP_PROJECT_REL_PATH="$DEMOAPP_REL/project.yml"
DEMOAPP_XCODEPROJ_REL="$DEMOAPP_REL/MSPDemoApp.xcodeproj"

mkdir -p "$SWIFTPM_DIR"

# List every Package.swift while ignoring build artifacts and Pods.
declare -a PACKAGE_FILES=()
while IFS= read -r pkg_file; do
  PACKAGE_FILES+=("$pkg_file")
done < <(find "$ROOT_DIR" -name Package.swift \
  ! -path '*/Pods/*' ! -path '*/DerivedData/*' ! -path '*/.build/*' \
  -print | LC_ALL=C sort)

if [[ ${#PACKAGE_FILES[@]-0} -eq 0 ]]; then
  echo "$LOG_PREFIX No Package.swift files found" >&2
fi

declare -a PACKAGE_NAMES=()
declare -a PACKAGE_REL_PATHS=()
if [[ ${#PACKAGE_FILES[@]-0} -gt 0 ]]; then
  for pkg in "${PACKAGE_FILES[@]}"; do
    pkg_dir="${pkg%/Package.swift}"
    pkg_name="$(basename "$pkg_dir")"
    rel_path="${pkg_dir#$ROOT_DIR/}"
    PACKAGE_NAMES+=("$pkg_name")
    PACKAGE_REL_PATHS+=("$rel_path")
  done
fi

# Write SwiftPM package manifest json for tooling/CI.
{
  echo "["
  for ((i=0; i<${#PACKAGE_NAMES[@]}; i++)); do
    name="${PACKAGE_NAMES[$i]}"
    rel="${PACKAGE_REL_PATHS[$i]}"
    suffix=",";
    if [[ $i -eq $((${#PACKAGE_NAMES[@]} - 1)) ]]; then
      suffix=""
    fi
    printf '  {"name":"%s","path":"%s"}%s\n' "$name" "$rel" "$suffix"
  done
  echo "]"
} > "$SWIFTPM_JSON"

declare -a SPM_APP_PRODUCTS=(
  "MSPCore"
  "MSPNovaAdapter"
  "PrebidAdapter"
  "MSPGoogleAdapter"
  "MSPFacebookAdapter"
  "MSPSharedLibraries"
  "MSPOMSDK"
  "MSPiOSCore"
  "NovaCore"
  "ShimmerWrapper"
  "FBAudienceNetworkWrapper"
  "IronSourceSDKWrapper"
  "OpenWrapSDKWrapper"
  "MintegralAdSDKWrapper"
  "MobileFuseSDKWrapper"
  "InMobiSDKWrapper"
  "UnityAdapter"
  "PubmaticAdapter"
  "MintegralAdapter"
  "MobilefuseAdapter"
  "InmobiAdapter"
)

# Helper to check if a package exists.
package_exists() {
  local name="$1"
  if [[ ${#PACKAGE_NAMES[@]-0} -eq 0 ]]; then
    return 1
  fi
  for candidate in "${PACKAGE_NAMES[@]-}"; do
    if [[ "$candidate" == "$name" ]]; then
      return 0
    fi
  done
  return 1
}

# Generate the XcodeGen project spec for MSPDemoApp.
mkdir -p "$(dirname "$PROJECT_SPEC")"
cat > "$PROJECT_SPEC" <<'YAML'
# This file is auto-generated by Scripts/workspace/update.sh
name: MSPDemoApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "15.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    DEVELOPMENT_TEAM: 4PEHUZX8QH
    PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoApp
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 3.6.13
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    INFOPLIST_FILE: MSPDemoApp/Info.plist
YAML

if [[ ${#PACKAGE_NAMES[@]} -eq 0 ]]; then
  echo "packages: {}" >> "$PROJECT_SPEC"
else
  echo "packages:" >> "$PROJECT_SPEC"
  for ((i=0; i<${#PACKAGE_NAMES[@]}; i++)); do
    raw_name="${PACKAGE_NAMES[$i]}"
    rel="../${PACKAGE_REL_PATHS[$i]}"
    cat >> "$PROJECT_SPEC" <<YAML
  ${raw_name}:
    name: ${raw_name}
    path: ${rel}
YAML
  done
fi

cat >> "$PROJECT_SPEC" <<'YAML'
targetTemplates:
  BaseAppTarget:
    type: application
    platform: iOS
    sources:
      - path: MSPDemoApp
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: 5.0
YAML
printf '        PODS_ROOT: "%s"\n' "$PODS_ROOT_REL" >> "$PROJECT_SPEC"
cat >> "$PROJECT_SPEC" <<'YAML'
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
targets:
  MSPDemoApp:
    templates:
      - BaseAppTarget
YAML
emit_demoapp_pods_config_files "$PROJECT_SPEC" "$DEMOAPP_DIR" "$DEMOAPP_PODS_XCCONFIG_DEBUG_REL" "$DEMOAPP_PODS_XCCONFIG_RELEASE_REL" "    "
cat >> "$PROJECT_SPEC" <<'YAML'
    prebuildScripts:
      - name: "[CP] Check Pods Manifest.lock"
        script: |
          if [ -z "${PODS_PODFILE_DIR_PATH}" ] || [ -z "${PODS_ROOT}" ]; then
            echo "error: CocoaPods environment variables are not set." >&2
            exit 1
          fi
          if [ ! -e "${PODS_ROOT}/Manifest.lock" ] || [ ! -e "${PODS_PODFILE_DIR_PATH}/Podfile.lock" ]; then
            echo "error: Run 'pod install' to generate Pods/Manifest.lock." >&2
            exit 1
          fi
          if ! diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" >/dev/null; then
            echo "error: Podfile.lock and Manifest.lock are out of sync. Run 'pod install'." >&2
            exit 1
          fi
        shell: /bin/sh
    postbuildScripts:
      - name: "[CP] Embed Pods Frameworks"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-frameworks.sh\""
        shell: /bin/sh
      - name: "[CP] Copy Pods Resources"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-resources.sh\""
        shell: /bin/sh
  MSPDemoApp-SPM:
    templates:
      - BaseAppTarget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoAppSPM
    configFiles:
      Debug: ../Configs/MSPDemoApp-Debug-SPM.xcconfig
      Release: ../Configs/MSPDemoApp-Release-SPM.xcconfig
YAML

if [[ ${#PACKAGE_NAMES[@]-0} -eq 0 ]]; then
  cat >> "$PROJECT_SPEC" <<'YAML'
    dependencies: []
YAML
else
  cat >> "$PROJECT_SPEC" <<'YAML'
    dependencies:
YAML
  for product in "${SPM_APP_PRODUCTS[@]}"; do
    if package_exists "$product"; then
      cat >> "$PROJECT_SPEC" <<YAML
        - package: ${product}
          product: ${product}
YAML
    else
      echo "$LOG_PREFIX Warning: Skipping unknown package '${product}'" >&2
    fi
  done
fi

cat >> "$PROJECT_SPEC" <<'YAML'
  MSPDemoAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MSPDemoAppTests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MSPDemoApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MSPDemoApp"
YAML
emit_demoapp_pods_config_files "$PROJECT_SPEC" "$DEMOAPP_DIR" "$DEMOAPP_PODS_XCCONFIG_DEBUG_REL" "$DEMOAPP_PODS_XCCONFIG_RELEASE_REL" "    "
cat >> "$PROJECT_SPEC" <<'YAML'
    dependencies:
      - target: MSPDemoApp
  MSPDemoAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MSPDemoAppUITests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
YAML
emit_demoapp_pods_config_files "$PROJECT_SPEC" "$DEMOAPP_DIR" "$DEMOAPP_PODS_XCCONFIG_DEBUG_REL" "$DEMOAPP_PODS_XCCONFIG_RELEASE_REL" "    "
if [[ -f "$DEMOAPP_DIR/$DEMOAPP_PODS_XCCONFIG_DEBUG_REL" ]] && \
   [[ -f "$DEMOAPP_DIR/$DEMOAPP_PODS_XCCONFIG_RELEASE_REL" ]]; then
  cat >> "$PROJECT_SPEC" <<YAML
    configFiles:
      Debug: ${DEMOAPP_PODS_XCCONFIG_DEBUG_REL}
      Release: ${DEMOAPP_PODS_XCCONFIG_RELEASE_REL}
YAML
fi
cat >> "$PROJECT_SPEC" <<'YAML'
    dependencies:
      - target: MSPDemoApp
YAML

# Add test targets if they are defined in Podfile
# Check Podfile for test target definitions
PODFILE="$ROOT_DIR/Podfile"
if [[ -f "$PODFILE" ]]; then
  TEST_TARGETS=("MSPCoreTests" "MSPiOSCoreTests" "NovaCoreTests" "AdapterTests")
  for test_target in "${TEST_TARGETS[@]}"; do
    # Check if target is defined in Podfile
    if grep -q "target '${test_target}'" "$PODFILE"; then
      pods_debug_config="$ROOT_DIR/Pods/Target Support Files/Pods-${test_target}/Pods-${test_target}.debug.xcconfig"
      pods_release_config="$ROOT_DIR/Pods/Target Support Files/Pods-${test_target}/Pods-${test_target}.release.xcconfig"
      
      cat >> "$PROJECT_SPEC" <<YAML
  ${test_target}:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ../../Tests/${test_target}
        excludes:
          - "**/.DS_Store"
YAML
      # Add configFiles only if Pods xcconfig files exist (after pod install)
      if [[ -f "$pods_debug_config" ]] && [[ -f "$pods_release_config" ]]; then
        cat >> "$PROJECT_SPEC" <<YAML
    configFiles:
      Debug: ../../Pods/Target Support Files/Pods-${test_target}/Pods-${test_target}.debug.xcconfig
      Release: ../../Pods/Target Support Files/Pods-${test_target}/Pods-${test_target}.release.xcconfig
YAML
      fi
      cat >> "$PROJECT_SPEC" <<YAML
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
        SWIFT_VERSION: "5.0"
        TEST_HOST: "\$(BUILT_PRODUCTS_DIR)/MSPDemoApp.app/\$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MSPDemoApp"
        PODS_ROOT: "\$(SRCROOT)/../../Pods"
        PODS_PODFILE_DIR_PATH: "\$(SRCROOT)/../.."
    dependencies:
      - target: MSPDemoApp
YAML
    fi
  done
fi

cat >> "$PROJECT_SPEC" <<'YAML'
schemes:
  MSPDemoApp:
    build:
      targets:
        MSPDemoApp: all
        MSPDemoAppTests: test
        MSPDemoAppUITests: test
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - target: MSPDemoAppTests
        - target: MSPDemoAppUITests
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  MSPDemoApp-SPM:
    build:
      targets:
        MSPDemoApp-SPM: all
    test:
      config: Debug
      targets: []
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  MSPTests:
    build:
      targets:
        MSPDemoApp: all
        MSPDemoAppTests: test
        MSPDemoAppUITests: test
        MSPCoreTests: test
        MSPiOSCoreTests: test
        NovaCoreTests: test
        AdapterTests: test
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: MSPCoreTests
          parallelizable: false
        - name: MSPiOSCoreTests
          parallelizable: false
        - name: NovaCoreTests
          parallelizable: false
        - name: AdapterTests
          parallelizable: false
YAML

# Generate the workspace specification so xcodegen can rebuild the .xcworkspace.
PROJECTS=()
while IFS= read -r proj; do
  PROJECTS+=("$proj")
done < <(find "$ROOT_DIR" -name '*.xcodeproj' \
  ! -path '*/DerivedData/*' ! -path '*/Pods/Pods.xcodeproj/*' \
  -print | LC_ALL=C sort)

pods_detected=0
{
  echo "workspace:"
  echo "  name: msp-ios-sdk"
  echo "  projects:"
  echo "    - name: MSPDemoApp"
  echo "      path: ${DEMOAPP_PROJECT_REL_PATH}"
  echo "      type: file"
  for proj in ${PROJECTS[@]+"${PROJECTS[@]}"}; do
    rel="${proj#$ROOT_DIR/}"
    # Skip the generated MSPDemoApp project - it will be created from the spec above.
    if [[ "$rel" == "$DEMOAPP_XCODEPROJ_REL" ]]; then
      continue
    fi
    if [[ "$rel" == "Pods/Pods.xcodeproj" ]]; then
      pods_detected=1
    fi
    project_name="$(basename "${rel%.*}")"
    echo "    - name: ${project_name}"
    echo "      path: ${rel}"
    echo "      type: file"
  done
  # Include Pods.xcodeproj if it exists (legacy mode, not used with :generate_multiple_pod_projects => true)
  if [[ $pods_detected -eq 0 ]] && [[ -d "$ROOT_DIR/Pods/Pods.xcodeproj" ]]; then
    echo "    - name: Pods"
    echo "      path: Pods/Pods.xcodeproj"
    echo "      type: file"
  fi
} > "$WORKSPACE_SPEC"

# Regenerate the .xcworkspace XML for Xcode consumers
mkdir -p "$WORKSPACE_PATH"
{
  cat <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
XML
  cat <<XML
   <FileRef
      location = "group:${DEMOAPP_XCODEPROJ_REL}">
   </FileRef>
XML
  for proj in ${PROJECTS[@]+"${PROJECTS[@]}"}; do
    rel="${proj#$ROOT_DIR/}"
    if [[ "$rel" == "$DEMOAPP_XCODEPROJ_REL" ]]; then
      continue
    fi
    cat <<XML
   <FileRef
      location = "group:${rel}">
   </FileRef>
XML
  done
  echo "</Workspace>"
} > "$WORKSPACE_DATA"

# R029e: Use xcodegen.sh module if available, fallback to direct call
if command -v xcodegen_generate &>/dev/null; then
  echo "$LOG_PREFIX Running xcodegen generate via xcodegen.sh module"
  if ! xcodegen_generate "$PROJECT_SPEC" "$(dirname "$PROJECT_SPEC")"; then
    echo "$LOG_PREFIX xcodegen failed. Ensure version 2.38.0+ is installed (run 'brew upgrade xcodegen')." >&2
  fi
else
  # Fallback to direct xcodegen call
  XCODEGEN_BIN="$(command -v xcodegen || true)"
  if [[ -z "$XCODEGEN_BIN" ]]; then
    echo "$LOG_PREFIX xcodegen is not installed. Install via 'brew install xcodegen' (2.38.0+ required) and re-run this script." >&2
  else
    echo "$LOG_PREFIX Running xcodegen generate"
    if ! "$XCODEGEN_BIN" generate --spec "$PROJECT_SPEC"; then
      echo "$LOG_PREFIX xcodegen failed. Ensure version 2.38.0+ is installed (run 'brew upgrade xcodegen')." >&2
    fi
  fi
fi

if [[ -f "$ROOT_DIR/Gemfile" ]]; then
  if [[ -n "${CI:-}" ]]; then
    echo "$LOG_PREFIX Running bundle exec pod install"
    if ! (cd "$ROOT_DIR" && bundle exec pod install); then
      echo "$LOG_PREFIX bundle exec pod install failed; please rerun locally." >&2
    fi
  else
    echo "$LOG_PREFIX Skipping pod install (run 'bundle exec pod install' locally to update Pods)."
  fi
fi

echo "$LOG_PREFIX Workspace spec -> $WORKSPACE_SPEC"
echo "$LOG_PREFIX Project spec -> $PROJECT_SPEC"
echo "$LOG_PREFIX SwiftPM packages -> $SWIFTPM_JSON"
