#!/usr/bin/env bash
# Pre-commit hook to prevent committing generated Xcode files
# This hook ensures the zero-diff switching guarantee is maintained

set -euo pipefail

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Patterns to block
BLOCKED_PATTERNS=(
    "MSPDemoApp/**/*.pbxproj"
    "MSPDemoApp/**/*.xcscheme"
    "**/*.xcworkspace"
    "xcshareddata/**"
    "xcuserdata/**"
    "DerivedData/**"
    "*.mode1v3"
    "*.mode2v3"
)

# Check if any blocked files are staged
BLOCKED_FOUND=false
BLOCKED_FILES=()

for pattern in "${BLOCKED_PATTERNS[@]}"; do
    # Use git diff --cached to check staged files
    while IFS= read -r file; do
        if [[ -n "$file" ]]; then
            BLOCKED_FOUND=true
            BLOCKED_FILES+=("$file")
        fi
    done < <(git diff --cached --name-only --diff-filter=ACMR | grep -E "$pattern" || true)
done

if [[ "$BLOCKED_FOUND" == "true" ]]; then
    echo ""
    echo -e "${RED}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${RED}║  PRE-COMMIT HOOK: Generated Xcode Files Detected              ║${NC}"
    echo -e "${RED}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${YELLOW}❌ DO NOT commit generated Xcode files!${NC}"
    echo ""
    echo "The following files are generated and should NOT be committed:"
    echo ""
    for file in "${BLOCKED_FILES[@]}"; do
        echo -e "  ${RED}✗${NC} $file"
    done
    echo ""
    echo "These files are generated from YAML specs and should be regenerated by:"
    echo ""
    echo "  ${YELLOW}xcodegen generate --spec MSPDemoApp/project.yml${NC}"
    echo ""
    echo "To fix this:"
    echo "  1. Unstage these files:"
    echo "     ${YELLOW}git restore --staged MSPDemoApp/**/*.pbxproj MSPDemoApp/**/*.xcscheme${NC}"
    echo ""
    echo "  2. If you need to regenerate project files, run:"
    echo "     ${YELLOW}xcodegen generate --spec MSPDemoApp/project.yml${NC}"
    echo ""
    echo "  3. Only commit source files (project.yml, workspace.yml, .swift, etc.)"
    echo ""
    echo -e "${RED}Commit blocked.${NC}"
    exit 1
fi

exit 0

