#!/usr/bin/env bash
# --- MSP Worktree Safety Guard (Patch M, shared) ---
# shellcheck source=/dev/null
_msp_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$_msp_root" ] && [ -f "$_msp_root/Scripts/lib/worktree_guard.sh" ]; then
  . "$_msp_root/Scripts/lib/worktree_guard.sh"
  msp_enforce_main_repo_or_exit
fi
unset _msp_root
# --- End MSP Worktree Safety Guard (Patch M, shared) ---
# Pre-commit hook to warn about generated Xcode files
# These files are nondeterministic and expected to change
# This hook provides awareness but does not block commits

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=Scripts/lib/paths.sh
source "$ROOT_DIR/Scripts/lib/paths.sh" 2>/dev/null || true
# shellcheck source=Scripts/lib/colors.sh
source "$ROOT_DIR/Scripts/lib/colors.sh" 2>/dev/null || true
# shellcheck source=Scripts/lib/ui.sh
source "$ROOT_DIR/Scripts/lib/ui.sh" 2>/dev/null || true

if command -v init_paths &>/dev/null; then
    init_paths
fi

# Patterns to check for generated Xcode files
CHECK_PATTERNS=(
    "MSPDemoApp/.*\.pbxproj"
    "MSPDemoApp/.*\.xcscheme"
    ".*\.xcworkspace"
    "xcshareddata/"
    "xcuserdata/"
)

# Check if any generated files are staged
DETECTED_FILES=()

for pattern in "${CHECK_PATTERNS[@]}"; do
    while IFS= read -r file; do
        if [[ -n "$file" ]]; then
            DETECTED_FILES+=("$file")
        fi
    done < <(git diff --cached --name-only --diff-filter=ACMR | grep -E "$pattern" || true)
done

if [[ ${#DETECTED_FILES[@]} -gt 0 ]]; then
    # Use UI system if available, otherwise fallback to simple echo
    if command -v log_warn &>/dev/null; then
        log::warn "GIT" "Generated Xcode files detected in commit"
        log::info "GIT" ""
        log::info "GIT" "The following files are generated and nondeterministic:"
        for file in "${DETECTED_FILES[@]}"; do
            log::info "GIT" "  • $file"
        done
        log::info "GIT" ""
        log::info "GIT" "These files are auto-generated by Xcode, SwiftPM, or CocoaPods."
        log::info "GIT" "They may change when:"
        log::info "GIT" "  - Xcode updates project metadata"
        log::info "GIT" "  - SwiftPM resolves packages"
        log::info "GIT" "  - CocoaPods regenerates integration files"
        log::info "GIT" ""
        log::info "GIT" "YAML files (project.yml, workspace.yml) are the source of truth."
        log::info "GIT" "Generated project files are expected to change and are acceptable to commit."
    else
        echo ""
        echo "⚠️  WARNING: Generated Xcode files detected in commit"
        echo ""
        echo "These files are nondeterministic and expected to change:"
        for file in "${DETECTED_FILES[@]}"; do
            echo "  • $file"
        done
        echo ""
        echo "YAML files (project.yml, workspace.yml) are the source of truth."
        echo "Generated project files are acceptable to commit."
    fi
fi

# Always exit 0 (warn-only, never block)
exit 0

