#!/bin/bash
# Minimal Podspec Generator for Release Mode Only
#
# Purpose: Generate release podspecs with correct binary paths
# Scope: ONLY used in MSP_RELEASE_TIER=release
# Input: Existing repo podspec + XCFramework paths
# Output: Build/ReleasePodspecs/*.podspec

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Source logging functions
if [[ -f "$ROOT_DIR/Scripts/lib/release-common.sh" ]]; then
    source "$ROOT_DIR/Scripts/lib/release-common.sh"
else
    log_info() { echo "[INFO] $*"; }
    log_error() { echo "[ERROR] $*" >&2; }
    log_success() { echo "[SUCCESS] $*"; }
fi

# ============================================================================
# Configuration
# ============================================================================

# Output directory for generated podspecs
GENERATED_PODSPECS_DIR="$ROOT_DIR/Build/ReleasePodspecs"

# ============================================================================
# Usage
# ============================================================================

show_usage() {
    cat <<EOF
Usage: $0 <POD_NAME> <VERSION>

Generate release podspec with binary XCFramework paths.

Arguments:
  POD_NAME    Pod module name (e.g., MSPSharedLibraries)
  VERSION     Release version (e.g., 0.8.8-real.1)

Example:
  $0 MSPSharedLibraries 0.8.8-real.1

Environment:
  ROOT_DIR    Repository root (auto-detected)

Output:
  Build/ReleasePodspecs/<POD_NAME>.podspec
EOF
}

# ============================================================================
# Parse Arguments
# ============================================================================

if [[ $# -lt 2 ]]; then
    show_usage
    exit 1
fi

POD_NAME="$1"
VERSION="$2"

# ============================================================================
# Validate Inputs
# ============================================================================

SOURCE_PODSPEC="$ROOT_DIR/${POD_NAME}.podspec"

if [[ ! -f "$SOURCE_PODSPEC" ]]; then
    log_error "Source podspec not found: $SOURCE_PODSPEC"
    exit 1
fi

XCFRAMEWORK_PATH="$ROOT_DIR/Build/XCFrameworks/${POD_NAME}.xcframework"

if [[ ! -d "$XCFRAMEWORK_PATH" ]]; then
    log_error "XCFramework not found: $XCFRAMEWORK_PATH"
    log_error "Run pre-release setup (Step 0) first to build XCFrameworks"
    exit 1
fi

# ============================================================================
# Generate Release Podspec
# ============================================================================

log_info "Generating release podspec for $POD_NAME v$VERSION"

# Create output directory
mkdir -p "$GENERATED_PODSPECS_DIR"

OUTPUT_PODSPEC="$GENERATED_PODSPECS_DIR/${POD_NAME}.podspec"

# ============================================================================
# Extract metadata from source podspec using awk/sed
# ============================================================================

log_info "Parsing source podspec: $SOURCE_PODSPEC"

# Extract key metadata fields from source podspec
extract_field() {
    local field="$1"
    local file="$2"
    grep -m 1 "spec\\.${field}" "$file" | head -1
}

# Start writing the podspec
cat > "$OUTPUT_PODSPEC" <<'EOF_HEADER'
Pod::Spec.new do |spec|

EOF_HEADER

# Extract and write metadata fields
{
    extract_field "name" "$SOURCE_PODSPEC"
    extract_field "summary" "$SOURCE_PODSPEC"
    extract_field "description" "$SOURCE_PODSPEC"
    extract_field "homepage" "$SOURCE_PODSPEC"
    extract_field "license" "$SOURCE_PODSPEC"
    extract_field "author" "$SOURCE_PODSPEC"
    extract_field "platform" "$SOURCE_PODSPEC"
    extract_field "ios\\.deployment_target" "$SOURCE_PODSPEC"
    extract_field "swift_version" "$SOURCE_PODSPEC"
    extract_field "requires_arc" "$SOURCE_PODSPEC"
    extract_field "static_framework" "$SOURCE_PODSPEC"
} | grep -v "^\s*#" >> "$OUTPUT_PODSPEC"

# Extract xcconfig (multiline handling)
awk '
/spec\.pod_target_xcconfig/ {
    print
    if ($0 ~ /\{/ && $0 !~ /\}/) {
        in_block = 1
        next
    }
}
in_block {
    print
    if ($0 ~ /\}/) {
        in_block = 0
    }
}
' "$SOURCE_PODSPEC" >> "$OUTPUT_PODSPEC"

awk '
/spec\.user_target_xcconfig/ {
    print
    if ($0 ~ /\{/ && $0 !~ /\}/) {
        in_block = 1
        next
    }
}
in_block {
    print
    if ($0 ~ /\}/) {
        in_block = 0
    }
}
' "$SOURCE_PODSPEC" >> "$OUTPUT_PODSPEC"

# Extract dependencies
grep "spec\\.dependency" "$SOURCE_PODSPEC" >> "$OUTPUT_PODSPEC" 2>/dev/null || true

# Add release-specific configuration
cat >> "$OUTPUT_PODSPEC" <<EOF_RELEASE

  # ═══════════════════════════════════════════════════════════════════════════
  # GENERATED FOR RELEASE (Binary Distribution)
  # Generated by: Scripts/release/generate_podspec.sh
  # ═══════════════════════════════════════════════════════════════════════════

  spec.version = "$VERSION"

  spec.source = {
    git: "https://github.com/ParticleMedia/msp-ios-sdk-public.git",
    tag: spec.version.to_s
  }

EOF_RELEASE

# Add vendored_frameworks based on pod name
if [[ "$POD_NAME" == "MSPSharedLibraries" ]]; then
    cat >> "$OUTPUT_PODSPEC" <<'EOF_VENDOR_MULTI'
  spec.vendored_frameworks = [
    "Binary/MSPSharedLibraries.xcframework",
    "ThirdParty/PrebidMobile/PrebidMobile.xcframework"
  ]
EOF_VENDOR_MULTI
else
    cat >> "$OUTPUT_PODSPEC" <<EOF_VENDOR_SINGLE
  spec.vendored_frameworks = "Binary/${POD_NAME}.xcframework"
EOF_VENDOR_SINGLE
fi

# Close the podspec
cat >> "$OUTPUT_PODSPEC" <<'EOF_FOOTER'

end
EOF_FOOTER

log_success "Generated release podspec: $OUTPUT_PODSPEC"
log_info "Location: $OUTPUT_PODSPEC"

# ============================================================================
# Validation
# ============================================================================

log_info "Validating generated podspec structure..."

if ! grep -q "spec.version.*$VERSION" "$OUTPUT_PODSPEC"; then
    log_error "Generated podspec missing correct version"
    exit 1
fi

if ! grep -q "spec.vendored_frameworks" "$OUTPUT_PODSPEC"; then
    log_error "Generated podspec missing vendored_frameworks"
    exit 1
fi

log_success "Podspec structure validated"
log_info "Next: Run 'pod spec lint $OUTPUT_PODSPEC --allow-warnings' to validate"

exit 0
