#!/usr/bin/env bash
# --- MSP Worktree Safety Guard (Patch L, shared) ---
# shellcheck source=/dev/null
. "$(git rev-parse --show-toplevel 2>/dev/null)/Scripts/lib/worktree_guard.sh"
msp_enforce_main_repo_or_exit
# --- End MSP Worktree Safety Guard (Patch L, shared) ---
# Auto-generate 15 verification test cases for MSP Release System

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CASES_DIR="$SCRIPT_DIR/cases"

mkdir -p "$CASES_DIR"

# Case Definitions (name, DRY_RUN, STRICT, URL)
# 12 matrix cases + 3 extended cases

cases=(
"A1_dry_off_strict_off_no_url|0|0|"
"A2_dry_off_strict_off_valid_url|0|0|https://github.com/ParticleMedia/msp-ios-sdk-public"
"A3_dry_off_strict_off_invalid_url|0|0|https://invalid.url/repo.git"

"B1_dry_off_strict_on_no_url|0|1|"
"B2_dry_off_strict_on_valid_url|0|1|https://github.com/ParticleMedia/msp-ios-sdk-public"
"B3_dry_off_strict_on_invalid_url|0|1|https://invalid.url/repo.git"

"C1_dry_on_strict_off_no_url|1|0|"
"C2_dry_on_strict_off_valid_url|1|0|https://github.com/ParticleMedia/msp-ios-sdk-public"
"C3_dry_on_strict_off_invalid_url|1|0|https://invalid.url/repo.git"

"D1_dry_on_strict_on_no_url|1|1|"
"D2_dry_on_strict_on_valid_url|1|1|https://github.com/ParticleMedia/msp-ios-sdk-public"
"D3_dry_on_strict_on_invalid_url|1|1|https://invalid.url/repo.git"

"E1_baseline_default|0|1|https://github.com/ParticleMedia/msp-ios-sdk-public"
"E2_pods_only|0|1|https://github.com/ParticleMedia/msp-ios-sdk-public"
"E3_spm_only|0|1|https://github.com/ParticleMedia/msp-ios-sdk-public"
)

echo "Generating ${#cases[@]} cases into: $CASES_DIR"

for entry in "${cases[@]}"; do
    IFS='|' read -r name dry strict url <<< "$entry"
    filepath="$CASES_DIR/${name}.sh"

    cat > "$filepath" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# ============================================
# Test Case: $name
# Auto-generated by generate_cases.sh
# ============================================

SCRIPT_ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/../../.." && pwd)"

# Load UI system
source "\$SCRIPT_ROOT/Scripts/lib/release-common.sh"

export DRY_RUN="$dry"
export VERIFY_SPM_STRICT="$strict"
export SPM_REMOTE_URL="$url"

# pods-only / spm-only overrides
if [[ "$name" == "E2_pods_only" ]]; then
    export SKIP_SPM=1
elif [[ "$name" == "E3_spm_only" ]]; then
    export SKIP_PODS=1
fi

echo "[CASE] Running: $name"
echo "  DRY_RUN=$dry"
echo "  VERIFY_SPM_STRICT=$strict"
echo "  SPM_REMOTE_URL='${url}'"

# Call main verify command
"\$SCRIPT_ROOT"/Scripts/msp-release.sh verify "0.0.0-test"
EOF

    chmod +x "$filepath"
    echo "Generated: $filepath"
done

