#!/bin/bash
# --- MSP Worktree Safety Guard (Patch K, shared) ---
# shellcheck source=/dev/null
if command -v git >/dev/null 2>&1; then
  MSP_REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  if [ -n "$MSP_REPO_ROOT" ] && [ -f "$MSP_REPO_ROOT/Scripts/lib/worktree_guard.sh" ]; then
    # shellcheck source=/dev/null
    . "$MSP_REPO_ROOT/Scripts/lib/worktree_guard.sh"
    msp_enforce_main_repo_or_exit
  fi
fi
# --- End MSP Worktree Safety Guard (Patch K, shared) ---
# ============================================================================
# Prepare DemoApp for CocoaPods Verification
# ============================================================================
# Purpose: Copy DemoApp into sandbox directory for CocoaPods verification
#
# Usage:   ./prepare_demoapp.sh <sandbox_path>
# ============================================================================

set -euo pipefail

# Source common utilities
source "$(dirname "$0")/../common/utils.sh"

# Ensure ROOT_DIR is detected
vr_detect_root_dir || {
    vr_log_error "Failed to detect ROOT_DIR"
    return 1
}

# ============================================================================
# Functions
# ============================================================================

prepare_demoapp() {
    local sandbox="$1"
    
    if [[ -z "$sandbox" ]]; then
        vr_log_error "Sandbox path required"
        return 1
    fi
    
    # 1. Create sandbox subfolder for DemoApp
    mkdir -p "$sandbox/DemoApp"
    
    # 2. Copy the DemoApp project template from $ROOT_DIR/Examples/MSPDemoApp/
    # Must copy: Sources/, Resources/, project.yml
    # DO NOT copy: Podfile (will be generated by patch_podfile.sh)
    
    local demoapp_source="$ROOT_DIR/Examples/MSPDemoApp"
    
    if [[ ! -d "$demoapp_source" ]]; then
        vr_log_error "DemoApp source not found: $demoapp_source"
        return 1
    fi
    
    # Copy Sources directory
    if [[ -d "$demoapp_source/Sources" ]]; then
        cp -R "$demoapp_source/Sources" "$sandbox/DemoApp/"
        vr_log_info "[PODS] Copied Sources directory"
    fi
    
    # Copy Resources directory
    if [[ -d "$demoapp_source/Resources" ]]; then
        cp -R "$demoapp_source/Resources" "$sandbox/DemoApp/"
        vr_log_info "[PODS] Copied Resources directory"
    fi
    
    # Copy project.yml
    if [[ -f "$demoapp_source/project.yml" ]]; then
        cp "$demoapp_source/project.yml" "$sandbox/DemoApp/"
        vr_log_info "[PODS] Copied project.yml"
    fi
    
    vr_log_info "[PODS] Prepared DemoApp in sandbox: $sandbox/DemoApp"
    
    return 0
}

# ============================================================================
# Main
# ============================================================================

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    prepare_demoapp "$@"
fi
