#!/usr/bin/env bash
# DemoApp configuration script - Enhanced version
set -euo pipefail

MODE="${1:---mode=pods-dev}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 Configuring DemoApp"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Mode: $MODE"

# ═══════════════════════════════════════════════════════════
# Parse mode
# ═══════════════════════════════════════════════════════════
if [[ "$MODE" == "--mode=pods-dev" ]]; then
    echo "Using pods-dev mode (all source pods)"
    RELEASE_MODE="0"
elif [[ "$MODE" == "--mode=pods-release" ]]; then
    echo "Using pods-release mode (binary core + source adapters)"
    RELEASE_MODE="1"
else
    echo "❌ Unknown mode: $MODE"
    echo "Usage: $0 --mode=pods-dev|--mode=pods-release"
    exit 1
fi

# ═══════════════════════════════════════════════════════════
# Check if Podfile exists
# ═══════════════════════════════════════════════════════════
if [ ! -f "Podfile" ]; then
    echo "❌ Podfile not found in DemoApp directory"
    echo "PWD: $(pwd)"
    exit 1
fi

echo "✅ Podfile found"

# ═══════════════════════════════════════════════════════════
# Configure Podfile based on mode
# ═══════════════════════════════════════════════════════════
# Podfiles typically use environment variables to switch modes:
# ENV['MSP_RELEASE'] == '1' -> Use binary XCFrameworks
# ENV['MSP_RELEASE'] == '0' or nil -> Use source pods

echo ""
echo "Configuring Podfile for $MODE mode..."

# Create or update .env file for pod install
cat > .env << EOF
# DemoApp Configuration
# Generated by configure.sh
MSP_RELEASE=$RELEASE_MODE
EOF

echo "✅ Created .env file with MSP_RELEASE=$RELEASE_MODE"

# ═══════════════════════════════════════════════════════════
# Clean previous Pods installation (if switching modes)
# ═══════════════════════════════════════════════════════════
if [ -d "Pods" ]; then
    echo ""
    echo "Cleaning previous Pods installation..."
    rm -rf Pods
    rm -rf Podfile.lock
    echo "✅ Cleaned Pods directory"
fi

# ═══════════════════════════════════════════════════════════
# Export environment variable for pod install
# ═══════════════════════════════════════════════════════════
export MSP_RELEASE=$RELEASE_MODE

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ DemoApp configured for $MODE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Environment:"
echo "  MSP_RELEASE=$RELEASE_MODE"
echo ""
echo "Next steps:"
echo "  1. Run: pod install"
echo "  2. Open DemoApp.xcworkspace"
echo "  3. Build and run"
