#!/usr/bin/env bash
# ============================================================================
# YAML-Only Workspace Generation
# ============================================================================
# Purpose: Generate ONLY YAML spec files (project.yml, workspace.yml) based on
#          current mode (SPM or Pods). NEVER modifies Xcode-generated files.
#
# Usage:   ./Scripts/target-switching/generate_workspace.sh [spm|pods]
# ============================================================================

set -euo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=Scripts/target-switching/common.sh
source "$SCRIPT_DIR/common.sh"

ensure_repo_root

TARGET_MODE="${1:-}"
if [[ -z "$TARGET_MODE" ]]; then
    # Auto-detect mode
    TARGET_MODE=$(detect_current_mode)
    if [[ "$TARGET_MODE" == "mixed" ]]; then
        log_error "Cannot auto-detect mode (mixed environment detected)"
        log_info "Please specify: $0 [spm|pods]"
        exit 1
    fi
fi

if [[ "$TARGET_MODE" != "spm" ]] && [[ "$TARGET_MODE" != "pods" ]]; then
    log_error "Invalid mode. Must be 'spm' or 'pods'"
    exit 1
fi

log_title "Generating YAML Specs: $TARGET_MODE mode"

# Find all Package.swift files (sorted for determinism)
PACKAGE_FILES=()
while IFS= read -r pkg_file; do
    PACKAGE_FILES+=("$pkg_file")
done < <(find "$ROOT_DIR" -name Package.swift \
    ! -path '*/Pods/*' ! -path '*/DerivedData/*' ! -path '*/.build/*' \
    -print | LC_ALL=C sort)

PACKAGE_NAMES=()
PACKAGE_REL_PATHS=()
for pkg in "${PACKAGE_FILES[@]}"; do
    pkg_dir="${pkg%/Package.swift}"
    pkg_name="$(basename "$pkg_dir")"
    rel_path="${pkg_dir#$ROOT_DIR/}"
    PACKAGE_NAMES+=("$pkg_name")
    PACKAGE_REL_PATHS+=("$rel_path")
done

# SPM app products (sorted alphabetically for determinism)
declare -a SPM_APP_PRODUCTS=(
    "FBAudienceNetworkWrapper"
    "InMobiSDKWrapper"
    "InmobiAdapter"
    "IronSourceSDKWrapper"
    "MintegralAdapter"
    "MintegralAdSDKWrapper"
    "MobileFuseSDKWrapper"
    "MobilefuseAdapter"
    "MSPCore"
    "MSPFacebookAdapter"
    "MSPGoogleAdapter"
    "MSPiOSCore"
    "MSPOMSDK"
    "MSPSharedLibraries"
    "NovaAdapter"
    "NovaCore"
    "OpenWrapSDKWrapper"
    "PrebidAdapter"
    "PubmaticAdapter"
    "ShimmerWrapper"
    "UnityAdapter"
)

package_exists() {
    local name="$1"
    for candidate in "${PACKAGE_NAMES[@]}"; do
        if [[ "$candidate" == "$name" ]]; then
            return 0
        fi
    done
    return 1
}

# Generate project.yml deterministically
log_section "Generating project.yml"
log_step "Generating project.yml"
mkdir -p "$(dirname "$PROJECT_SPEC")"

# Generate to temporary file first for comparison
TEMP_PROJECT_SPEC="${PROJECT_SPEC}.tmp"

{
    cat <<'YAML'
# This file is auto-generated by Scripts/target-switching/generate_workspace.sh
# DO NOT EDIT MANUALLY - changes will be overwritten
name: MSPDemoApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "15.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 4PEHUZX8QH
    INFOPLIST_FILE: MSPDemoApp/Info.plist
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    MARKETING_VERSION: 0.0.117
    PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoApp
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: "1,2"
YAML

    # Add packages section (sorted alphabetically)
    if [[ ${#PACKAGE_NAMES[@]} -eq 0 ]]; then
        echo "packages: {}"
    else
        echo "packages:"
        # Sort package names for determinism
        IFS=$'\n' sorted_packages=($(printf '%s\n' "${PACKAGE_NAMES[@]}" | LC_ALL=C sort))
        for pkg_name in "${sorted_packages[@]}"; do
            # Find corresponding path
            for ((i=0; i<${#PACKAGE_NAMES[@]}; i++)); do
                if [[ "${PACKAGE_NAMES[$i]}" == "$pkg_name" ]]; then
                    rel="../${PACKAGE_REL_PATHS[$i]}"
                    cat <<YAML
  ${pkg_name}:
    name: ${pkg_name}
    path: ${rel}
YAML
                    break
                fi
            done
        done
    fi

    cat <<'YAML'
targetTemplates:
  BaseAppTarget:
    type: application
    platform: iOS
    sources:
      - path: MSPDemoApp
    info:
      path: MSPDemoApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: 5.0
YAML
    # Add PODS_ROOT only in Pods mode (for BaseAppTarget template)
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
        PODS_ROOT: "$(SRCROOT)/../Pods"
YAML
    fi
    cat <<'YAML'
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
targets:
YAML

    # MSPDemoApp target (CocoaPods only)
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
  MSPDemoApp:
    templates:
      - BaseAppTarget
    configFiles:
      Debug: ../Pods/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp.debug.xcconfig
      Release: ../Pods/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp.release.xcconfig
    prebuildScripts:
      - name: "[CP] Check Pods Manifest.lock"
        script: |
          if [ -z "${PODS_PODFILE_DIR_PATH}" ] || [ -z "${PODS_ROOT}" ]; then
            echo "error: CocoaPods environment variables are not set." >&2
            exit 1
          fi
          if [ ! -e "${PODS_ROOT}/Manifest.lock" ] || [ ! -e "${PODS_PODFILE_DIR_PATH}/Podfile.lock" ]; then
            echo "error: Run 'pod install' to generate Pods/Manifest.lock." >&2
            exit 1
          fi
          if ! diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" >/dev/null; then
            echo "error: Podfile.lock and Manifest.lock are out of sync. Run 'pod install'." >&2
            exit 1
          fi
        shell: /bin/sh
    postbuildScripts:
      - name: "[CP] Copy Pods Resources"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-resources.sh\""
        shell: /bin/sh
      - name: "[CP] Embed Pods Frameworks"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-frameworks.sh\""
        shell: /bin/sh
YAML
    fi

    # MSPDemoApp-SPM target (SPM only)
    if [[ "$TARGET_MODE" == "spm" ]]; then
        cat <<'YAML'
  MSPDemoApp-SPM:
    templates:
      - BaseAppTarget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoAppSPM
    configFiles:
      Debug: ../Configs/MSPDemoApp-Debug-SPM.xcconfig
      Release: ../Configs/MSPDemoApp-Release-SPM.xcconfig
    dependencies:
YAML
        # Sort products for determinism
        IFS=$'\n' sorted_products=($(printf '%s\n' "${SPM_APP_PRODUCTS[@]}" | LC_ALL=C sort))
        for product in "${sorted_products[@]}"; do
            if package_exists "$product"; then
                cat <<YAML
      - package: ${product}
        product: ${product}
YAML
            fi
        done
    fi

    # Test targets (only for Pods mode)
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
  MSPDemoAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MSPDemoAppTests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MSPDemoApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MSPDemoApp"
    dependencies:
      - target: MSPDemoApp
  MSPDemoAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MSPDemoAppUITests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - target: MSPDemoApp
YAML
    fi

    # Schemes (sorted for determinism)
    cat <<'YAML'
schemes:
YAML
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
  MSPDemoApp:
    build:
      targets:
        MSPDemoApp: all
        MSPDemoAppTests: test
        MSPDemoAppUITests: test
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - target: MSPDemoAppTests
        - target: MSPDemoAppUITests
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
YAML
    else
        cat <<'YAML'
  MSPDemoApp-SPM:
    build:
      targets:
        MSPDemoApp-SPM: all
    test:
      config: Debug
      targets: []
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
YAML
    fi
} > "$TEMP_PROJECT_SPEC"

# Compare with existing file and only write if different
if [[ -f "$PROJECT_SPEC" ]] && cmp -s "$PROJECT_SPEC" "$TEMP_PROJECT_SPEC"; then
    rm -f "$TEMP_PROJECT_SPEC"
    log_success "project.yml unchanged (already up-to-date)"
else
    mv "$TEMP_PROJECT_SPEC" "$PROJECT_SPEC"
    log_success "project.yml generated"
fi

# Generate workspace.yml deterministically
log_section "Generating workspace.yml"
log_step "Generating workspace.yml"

# Find all .xcodeproj files (excluding Pods and build artifacts, sorted for determinism)
PROJECTS=()
if [[ "$TARGET_MODE" == "spm" ]]; then
    # SPM mode: exclude all Pods projects
    while IFS= read -r proj; do
        PROJECTS+=("$proj")
    done < <(find "$ROOT_DIR" -name '*.xcodeproj' \
        ! -path '*/DerivedData/*' ! -path '*/Pods/*' \
        -print | LC_ALL=C sort)
else
    # Pods mode: exclude only Pods/Pods.xcodeproj internals, but include individual pod projects
    while IFS= read -r proj; do
        PROJECTS+=("$proj")
    done < <(find "$ROOT_DIR" -name '*.xcodeproj' \
        ! -path '*/DerivedData/*' ! -path '*/Pods/Pods.xcodeproj/*' \
        -print | LC_ALL=C sort)
fi

TEMP_WORKSPACE_SPEC="${WORKSPACE_SPEC}.tmp"

{
    cat <<'YAML'
# This file is auto-generated by Scripts/target-switching/generate_workspace.sh
# DO NOT EDIT MANUALLY - changes will be overwritten
workspace:
  name: msp-ios-sdk
  projects:
    - name: MSPDemoApp
      path: MSPDemoApp/project.yml
      type: file
YAML
    
    # Add all found projects (excluding generated MSPDemoApp, sorted for determinism)
    for proj in "${PROJECTS[@]}"; do
        rel="${proj#$ROOT_DIR/}"
        if [[ "$rel" == "MSPDemoApp/MSPDemoApp.xcodeproj" ]]; then
            continue
        fi
        project_name="$(basename "${rel%.*}")"
        printf "    - name: %s\n" "$project_name"
        printf "      path: %s\n" "$rel"
        printf "      type: file\n"
    done
    
    # Only include Pods project if in Pods mode AND it exists
    if [[ "$TARGET_MODE" == "pods" ]] && [[ -d "$PODS_DIR/Pods.xcodeproj" ]]; then
        cat <<'YAML'
    - name: Pods
      path: Pods/Pods.xcodeproj
      type: file
YAML
    fi
} > "$TEMP_WORKSPACE_SPEC"

# Compare with existing file and only write if different
if [[ -f "$WORKSPACE_SPEC" ]] && cmp -s "$WORKSPACE_SPEC" "$TEMP_WORKSPACE_SPEC"; then
    rm -f "$TEMP_WORKSPACE_SPEC"
    log_success "workspace.yml unchanged (already up-to-date)"
else
    mv "$TEMP_WORKSPACE_SPEC" "$WORKSPACE_SPEC"
    log_success "workspace.yml generated"
fi

log_title "YAML Generation Complete"
log_success "YAML specs generated for $TARGET_MODE mode"
log_info "Note: Xcode project files are NOT modified by this script"
log_info "Run 'xcodegen generate' manually if you need to regenerate Xcode projects"
