#!/usr/bin/env bash
# ============================================================================
# YAML-Only Workspace Generation
# ============================================================================
# Purpose: Generate ONLY YAML spec files (project.yml, workspace.yml) based on
#          current mode (SPM or Pods). NEVER modifies Xcode-generated files.
#
# Usage:   ./Scripts/target-switching/generate_workspace.sh [spm|pods]
# ============================================================================

set -euo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=Scripts/target-switching/common.sh
source "$SCRIPT_DIR/common.sh"

ensure_repo_root

TARGET_MODE="${1:-}"
if [[ -z "$TARGET_MODE" ]]; then
    # Auto-detect mode
    TARGET_MODE=$(detect_current_mode)
    if [[ "$TARGET_MODE" == "mixed" ]]; then
        log_error "Cannot auto-detect mode (mixed environment detected)"
        log_info "Please specify: $0 [spm|pods]"
        exit 1
    fi
fi

if [[ "$TARGET_MODE" != "spm" ]] && [[ "$TARGET_MODE" != "pods" ]]; then
    log_error "Invalid mode. Must be 'spm' or 'pods'"
    exit 1
fi

log_title "Generating YAML Specs: $TARGET_MODE mode"

# Find all Package.swift files (sorted for determinism)
PACKAGE_FILES=()
while IFS= read -r pkg_file; do
    PACKAGE_FILES+=("$pkg_file")
done < <(find "$ROOT_DIR" -name Package.swift \
    ! -path '*/Pods/*' ! -path '*/DerivedData/*' ! -path '*/.build/*' \
    -print | LC_ALL=C sort)

PACKAGE_NAMES=()
PACKAGE_REL_PATHS=()
for pkg in "${PACKAGE_FILES[@]}"; do
    pkg_dir="${pkg%/Package.swift}"
    pkg_name="$(basename "$pkg_dir")"
    rel_path="${pkg_dir#$ROOT_DIR/}"
    PACKAGE_NAMES+=("$pkg_name")
    PACKAGE_REL_PATHS+=("$rel_path")
done

# SPM app products (sorted alphabetically for determinism)
declare -a SPM_APP_PRODUCTS=(
    "FBAudienceNetworkWrapper"
    "InMobiSDKWrapper"
    "InmobiAdapter"
    "IronSourceSDKWrapper"
    "MintegralAdapter"
    "MintegralAdSDKWrapper"
    "MobileFuseSDKWrapper"
    "MobilefuseAdapter"
    "MSPCore"
    "MSPFacebookAdapter"
    "MSPGoogleAdapter"
    "MSPiOSCore"
    "MSPOMSDK"
    "MSPSharedLibraries"
    "NovaAdapter"
    "NovaCore"
    "OpenWrapSDKWrapper"
    "PrebidAdapter"
    "PubmaticAdapter"
    "ShimmerWrapper"
    "UnityAdapter"
)

package_exists() {
    local name="$1"
    for candidate in "${PACKAGE_NAMES[@]}"; do
        if [[ "$candidate" == "$name" ]]; then
            return 0
        fi
    done
    return 1
}

# Generate project.yml deterministically
log_section "Generating project.yml"
log_step "Generating project.yml"
mkdir -p "$(dirname "$PROJECT_SPEC")"

# Generate to temporary file first for comparison
TEMP_PROJECT_SPEC="${PROJECT_SPEC}.tmp"

{
    cat <<'YAML'
# This file is auto-generated by Scripts/target-switching/generate_workspace.sh
# DO NOT EDIT MANUALLY - changes will be overwritten
name: MSPDemoApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "15.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 4PEHUZX8QH
    INFOPLIST_FILE: MSPDemoApp/Info.plist
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    MARKETING_VERSION: 0.0.117
    PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoApp
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: "1,2"
YAML

    # Add packages section (sorted alphabetically)
    # In Pods mode: DO NOT include SwiftPM packages (empty packages block)
    # In SPM mode: Include all discovered local packages
    if [[ "$TARGET_MODE" == "pods" ]]; then
        # Pods mode: empty packages to prevent SwiftPM resolution
        echo "packages: {}"
    elif [[ ${#PACKAGE_NAMES[@]} -eq 0 ]]; then
        # SPM mode but no packages found
        echo "packages: {}"
    else
        # SPM mode: include all discovered packages
        echo "packages:"
        # Sort package names for determinism
        IFS=$'\n' sorted_packages=($(printf '%s\n' "${PACKAGE_NAMES[@]}" | LC_ALL=C sort))
        for pkg_name in "${sorted_packages[@]}"; do
            # Find corresponding path
            for ((i=0; i<${#PACKAGE_NAMES[@]}; i++)); do
                if [[ "${PACKAGE_NAMES[$i]}" == "$pkg_name" ]]; then
                    rel="../${PACKAGE_REL_PATHS[$i]}"
                    cat <<YAML
  ${pkg_name}:
    name: ${pkg_name}
    path: ${rel}
YAML
                    break
                fi
            done
        done
    fi

    cat <<'YAML'
targetTemplates:
  BaseAppTarget:
    type: application
    platform: iOS
    sources:
      - path: MSPDemoApp
    info:
      path: MSPDemoApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: 5.0
YAML
    # Add PODS_ROOT only in Pods mode (for BaseAppTarget template)
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
        PODS_ROOT: "$(SRCROOT)/../../Pods"
YAML
    fi
    cat <<'YAML'
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
targets:
YAML

    # MSPDemoApp target (CocoaPods only)
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
  MSPDemoApp:
    templates:
      - BaseAppTarget
    configFiles:
      Debug: ../../Pods/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp.debug.xcconfig
      Release: ../../Pods/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp.release.xcconfig
    prebuildScripts:
      - name: "[CP] Check Pods Manifest.lock"
        script: |
          if [ -z "${PODS_PODFILE_DIR_PATH}" ] || [ -z "${PODS_ROOT}" ]; then
            echo "error: CocoaPods environment variables are not set." >&2
            exit 1
          fi
          if [ ! -e "${PODS_ROOT}/Manifest.lock" ] || [ ! -e "${PODS_PODFILE_DIR_PATH}/Podfile.lock" ]; then
            echo "error: Run 'pod install' to generate Pods/Manifest.lock." >&2
            exit 1
          fi
          if ! diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" >/dev/null; then
            echo "error: Podfile.lock and Manifest.lock are out of sync. Run 'pod install'." >&2
            exit 1
          fi
        shell: /bin/sh
    postbuildScripts:
      - name: "[CP] Copy Pods Resources"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-resources.sh\""
        shell: /bin/sh
      - name: "[CP] Embed Pods Frameworks"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-frameworks.sh\""
        shell: /bin/sh
YAML
    fi

    # MSPDemoApp-SPM target (SPM only)
    if [[ "$TARGET_MODE" == "spm" ]]; then
        cat <<'YAML'
  MSPDemoApp-SPM:
    templates:
      - BaseAppTarget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoAppSPM
    configFiles:
      Debug: ../Configs/MSPDemoApp-Debug-SPM.xcconfig
      Release: ../Configs/MSPDemoApp-Release-SPM.xcconfig
    dependencies:
YAML
        # Sort products for determinism
        IFS=$'\n' sorted_products=($(printf '%s\n' "${SPM_APP_PRODUCTS[@]}" | LC_ALL=C sort))
        for product in "${sorted_products[@]}"; do
            if package_exists "$product"; then
                cat <<YAML
      - package: ${product}
        product: ${product}
YAML
            fi
        done
    fi

    # Test targets (only for Pods mode)
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
  MSPDemoAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MSPDemoAppTests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MSPDemoApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MSPDemoApp"
    dependencies:
      - target: MSPDemoApp
  MSPDemoAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MSPDemoAppUITests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - target: MSPDemoApp
YAML
    fi

    # Schemes (sorted for determinism)
    cat <<'YAML'
schemes:
YAML
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
  MSPDemoApp:
    build:
      targets:
        MSPDemoApp: all
        MSPDemoAppTests: test
        MSPDemoAppUITests: test
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - target: MSPDemoAppTests
        - target: MSPDemoAppUITests
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
YAML
    else
        cat <<'YAML'
  MSPDemoApp-SPM:
    build:
      targets:
        MSPDemoApp-SPM: all
    test:
      config: Debug
      targets: []
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
YAML
    fi
} > "$TEMP_PROJECT_SPEC"

# Compare with existing file and only write if different
if [[ -f "$PROJECT_SPEC" ]] && cmp -s "$PROJECT_SPEC" "$TEMP_PROJECT_SPEC"; then
    rm -f "$TEMP_PROJECT_SPEC"
    log_success "project.yml unchanged (already up-to-date)"
else
    mv "$TEMP_PROJECT_SPEC" "$PROJECT_SPEC"
    log_success "project.yml generated"
fi

# Generate workspace.yml deterministically
log_section "Generating workspace.yml"
log_step "Generating workspace.yml"

# Find all .xcodeproj files (excluding Pods and build artifacts, sorted for determinism)
# NOTE: Modules with project.yml (XcodeGen-managed) should use project.yml, not .xcodeproj
PROJECTS=()
# Initialize empty array
# Initialize PROJECTS array
XCODEGEN_PROJECTS=()
# Initialize PROJECTS array

# Discover XcodeGen-managed modules (project.yml takes precedence over .xcodeproj)
# Find all project.yml files in Sources/ and Examples/ directories
# Exclude Pods/, Build/, .generated/ from search
while IFS= read -r project_yml; do
    # Get relative path from ROOT_DIR
    rel_path="${project_yml#$ROOT_DIR/}"
    # Skip if in excluded directories
    if [[ "$rel_path" == Pods/* ]] || [[ "$rel_path" == Build/* ]] || [[ "$rel_path" == .generated/* ]]; then
        continue
    fi
    XCODEGEN_PROJECTS+=("$rel_path")
done < <(find "$ROOT_DIR/Sources" "$ROOT_DIR/Examples" -name "project.yml" -type f 2>/dev/null | LC_ALL=C sort)

if [[ "$TARGET_MODE" == "spm" ]]; then
    # SPM mode: exclude all Pods projects
    log_info "[generate_workspace] SPM mode: excluded Pods/Pods.xcodeproj"
    while IFS= read -r proj; do
        # Defensive check: skip any Pods-related paths
        if [[ "$proj" == *"Pods"* ]] || [[ "$proj" == *"Pods.xcodeproj" ]] || [[ "$proj" == */Pods/* ]]; then
            continue
        fi
        # Skip NovaCore.xcodeproj if NovaCore/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Core/NovaCore/NovaCore.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/NovaCore/project.yml" ]]; then
            continue
        fi
        # Skip MSPCore.xcodeproj if MSPCore/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Core/MSPCore/MSPCore.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPCore/project.yml" ]]; then
            continue
        fi
        # Skip MSPOMSDK.xcodeproj if MSPOMSDK/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Core/MSPOMSDK/MSPOMSDK.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPOMSDK/project.yml" ]]; then
            continue
        fi
        # Skip MSPSharedLibraries.xcodeproj if MSPSharedLibraries/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Core/MSPSharedLibraries/MSPSharedLibraries.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPSharedLibraries/project.yml" ]]; then
            continue
        fi
        # Skip NovaAdapter.xcodeproj if NovaAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/NovaAdapter/NovaAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/NovaAdapter/project.yml" ]]; then
            continue
        fi
        # Skip PrebidAdapter.xcodeproj if PrebidAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/PrebidAdapter/PrebidAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/PrebidAdapter/project.yml" ]]; then
            continue
        fi
        # Skip MSPGoogleAdapter.xcodeproj if MSPGoogleAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/MSPGoogleAdapter/MSPGoogleAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MSPGoogleAdapter/project.yml" ]]; then
            continue
        fi
        # Skip MSPFacebookAdapter.xcodeproj if MSPFacebookAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/MSPFacebookAdapter/MSPFacebookAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MSPFacebookAdapter/project.yml" ]]; then
            continue
        fi
        # Skip InmobiAdapter.xcodeproj if InmobiAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/InmobiAdapter/InmobiAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/InmobiAdapter/project.yml" ]]; then
            continue
        fi
        # Skip MintegralAdapter.xcodeproj if MintegralAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/MintegralAdapter/MintegralAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MintegralAdapter/project.yml" ]]; then
            continue
        fi
        # Skip MobilefuseAdapter.xcodeproj if MobilefuseAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/MobilefuseAdapter/MobilefuseAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MobilefuseAdapter/project.yml" ]]; then
            continue
        fi
        # Skip PubmaticAdapter.xcodeproj if PubmaticAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/PubmaticAdapter/PubmaticAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/PubmaticAdapter/project.yml" ]]; then
            continue
        fi
        # Skip UnityAdapter.xcodeproj if UnityAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/UnityAdapter/UnityAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/UnityAdapter/project.yml" ]]; then
            continue
        fi
        # Skip AmazonAdapter.xcodeproj if AmazonAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/AmazonAdapter/AmazonAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/AmazonAdapter/project.yml" ]]; then
            continue
        fi
        PROJECTS+=("$proj")
    done < <(find "$ROOT_DIR" -name '*.xcodeproj' \
        ! -path '*/DerivedData/*' ! -path '*/Pods/*' \
        -print | LC_ALL=C sort)
else
    # Pods mode: exclude ALL Pods projects (including individual pod projects)
    # We'll add Pods/Pods.xcodeproj separately at the end
    while IFS= read -r proj; do
        # Skip NovaCore.xcodeproj if NovaCore/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Core/NovaCore/NovaCore.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/NovaCore/project.yml" ]]; then
            continue
        fi
        # Skip MSPCore.xcodeproj if MSPCore/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Core/MSPCore/MSPCore.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPCore/project.yml" ]]; then
            continue
        fi
        # Skip MSPOMSDK.xcodeproj if MSPOMSDK/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Core/MSPOMSDK/MSPOMSDK.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPOMSDK/project.yml" ]]; then
            continue
        fi
        # Skip MSPSharedLibraries.xcodeproj if MSPSharedLibraries/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Core/MSPSharedLibraries/MSPSharedLibraries.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPSharedLibraries/project.yml" ]]; then
            continue
        fi
        # Skip NovaAdapter.xcodeproj if NovaAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/NovaAdapter/NovaAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/NovaAdapter/project.yml" ]]; then
            continue
        fi
        # Skip PrebidAdapter.xcodeproj if PrebidAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/PrebidAdapter/PrebidAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/PrebidAdapter/project.yml" ]]; then
            continue
        fi
        # Skip MSPGoogleAdapter.xcodeproj if MSPGoogleAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/MSPGoogleAdapter/MSPGoogleAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MSPGoogleAdapter/project.yml" ]]; then
            continue
        fi
        # Skip MSPFacebookAdapter.xcodeproj if MSPFacebookAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/MSPFacebookAdapter/MSPFacebookAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MSPFacebookAdapter/project.yml" ]]; then
            continue
        fi
        # Skip InmobiAdapter.xcodeproj if InmobiAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/InmobiAdapter/InmobiAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/InmobiAdapter/project.yml" ]]; then
            continue
        fi
        # Skip MintegralAdapter.xcodeproj if MintegralAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/MintegralAdapter/MintegralAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MintegralAdapter/project.yml" ]]; then
            continue
        fi
        # Skip MobilefuseAdapter.xcodeproj if MobilefuseAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/MobilefuseAdapter/MobilefuseAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MobilefuseAdapter/project.yml" ]]; then
            continue
        fi
        # Skip PubmaticAdapter.xcodeproj if PubmaticAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/PubmaticAdapter/PubmaticAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/PubmaticAdapter/project.yml" ]]; then
            continue
        fi
        # Skip UnityAdapter.xcodeproj if UnityAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/UnityAdapter/UnityAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/UnityAdapter/project.yml" ]]; then
            continue
        fi
        # Skip AmazonAdapter.xcodeproj if AmazonAdapter/project.yml exists (XcodeGen-managed)
        if [[ "$proj" == *"Sources/Adapters/AmazonAdapter/AmazonAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/AmazonAdapter/project.yml" ]]; then
            continue
        fi
        PROJECTS+=("$proj")
    done < <(find "$ROOT_DIR" -name '*.xcodeproj' \
        ! -path '*/DerivedData/*' ! -path '*/Pods/*' \
        -print | LC_ALL=C sort)
fi

TEMP_WORKSPACE_SPEC="${WORKSPACE_SPEC}.tmp"

{
    cat <<'YAML'
# This file is auto-generated by Scripts/target-switching/generate_workspace.sh
# DO NOT EDIT MANUALLY - changes will be overwritten
workspace:
  name: msp-ios-sdk
  projects:
    - name: MSPDemoApp
      path: Examples/MSPDemoApp/project.yml
      type: file
YAML
    
    # In Pods mode: ONLY include MSPDemoApp and Pods - exclude ALL SDK source projects
    if [[ "$TARGET_MODE" != "pods" ]]; then
        # Add XcodeGen-managed projects (project.yml files) first
        for proj_yml in "${XCODEGEN_PROJECTS[@]}"; do
            project_name="$(basename "$(dirname "$proj_yml")")"
            printf "    - name: %s\n" "$project_name"
            printf "      path: %s\n" "$proj_yml"
            printf "      type: file\n"
        done
        
        # Add all found .xcodeproj projects (excluding generated MSPDemoApp and XcodeGen-managed modules, sorted for determinism)
        if [[ ${#PROJECTS[@]} -gt 0 ]]; then
            for proj in "${PROJECTS[@]}"; do
            rel="${proj#$ROOT_DIR/}"
            # Defensive check: skip any Pods-related paths in SPM mode
            if [[ "$TARGET_MODE" == "spm" ]]; then
                if [[ "$rel" == *"Pods"* ]] || [[ "$rel" == *"Pods.xcodeproj" ]] || [[ "$rel" == */Pods/* ]]; then
                    continue
                fi
            fi
            if [[ "$rel" == "Examples/Examples/MSPDemoApp/MSPDemoApp.xcodeproj" ]]; then
                continue
            fi
            # Skip if this module has a project.yml (already included above)
            project_dir="$(dirname "$rel")"
            if [[ -f "$ROOT_DIR/$project_dir/project.yml" ]]; then
                continue
            fi
            # Skip NovaCore, MSPCore, MSPOMSDK, and MSPSharedLibraries if they have project.yml (already included above)
            if [[ "$rel" == "Sources/Core/NovaCore/NovaCore.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/NovaCore/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Core/MSPCore/MSPCore.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPCore/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Core/MSPOMSDK/MSPOMSDK.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPOMSDK/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Core/MSPSharedLibraries/MSPSharedLibraries.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPSharedLibraries/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Core/MSPiOSCore/MSPiOSCore.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Core/MSPiOSCore/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/NovaAdapter/NovaAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/NovaAdapter/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/PrebidAdapter/PrebidAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/PrebidAdapter/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/MSPGoogleAdapter/MSPGoogleAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MSPGoogleAdapter/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/MSPFacebookAdapter/MSPFacebookAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MSPFacebookAdapter/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/InmobiAdapter/InmobiAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/InmobiAdapter/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/MintegralAdapter/MintegralAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MintegralAdapter/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/MobilefuseAdapter/MobilefuseAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/MobilefuseAdapter/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/PubmaticAdapter/PubmaticAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/PubmaticAdapter/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/UnityAdapter/UnityAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/UnityAdapter/project.yml" ]]; then
                continue
            fi
            if [[ "$rel" == "Sources/Adapters/AmazonAdapter/AmazonAdapter.xcodeproj" ]] && [[ -f "$ROOT_DIR/Sources/Adapters/AmazonAdapter/project.yml" ]]; then
                continue
            fi
                project_name="$(basename "${rel%.*}")"
                printf "    - name: %s\n" "$project_name"
                printf "      path: %s\n" "$rel"
                printf "      type: file\n"
            done
        fi
    fi
    
    # Only include Pods project if in Pods mode AND it exists
    # Make sure it's not already included (shouldn't be, since we exclude all Pods/*)
    if [[ "$TARGET_MODE" == "pods" ]] && [[ -d "$PODS_DIR/Pods.xcodeproj" ]]; then
        cat <<'YAML'
    - name: Pods
      path: Pods/Pods.xcodeproj
      type: file
YAML
    fi
} > "$TEMP_WORKSPACE_SPEC"

# Compare with existing file and only write if different
if [[ -f "$WORKSPACE_SPEC" ]] && cmp -s "$WORKSPACE_SPEC" "$TEMP_WORKSPACE_SPEC"; then
    rm -f "$TEMP_WORKSPACE_SPEC"
    log_success "workspace.yml unchanged (already up-to-date)"
else
    mv "$TEMP_WORKSPACE_SPEC" "$WORKSPACE_SPEC"
    log_success "workspace.yml generated"
fi

log_info "[generate_workspace] workspace.yml generation complete"

log_info "[xcodegen] Generating .xcworkspace via XcodeGen..."

# Ensure workspace.yml exists
if [[ ! -f "workspace.yml" ]]; then
    log_error "[xcodegen] workspace.yml not found — cannot generate workspace"
    exit 1
fi

# Step 1: Generate all project.yml files referenced in workspace.yml
log_step "Generating project files from project.yml specs"
PROJECT_YML_FILES=()
while IFS= read -r line; do
    # Match lines like "path: Examples/MSPDemoApp/project.yml" or "path: NovaCore/project.yml"
    if [[ "$line" =~ ^[[:space:]]*path:[[:space:]]*(.+\.yml)$ ]]; then
        project_path="${BASH_REMATCH[1]}"
        if [[ -f "$ROOT_DIR/$project_path" ]]; then
            PROJECT_YML_FILES+=("$project_path")
        fi
    fi
done < <(grep -E "^[[:space:]]*path:" "$WORKSPACE_SPEC" || true)

# Generate each project.yml file
# Note: Some projects may fail if Pods aren't installed yet - that's OK, they'll be generated after pod install
FAILED_PROJECTS=()
# Initialize PROJECTS array
for project_yml in "${PROJECT_YML_FILES[@]}"; do
    log_info "[xcodegen] Generating project from $project_yml"
    if ! xcodegen generate --spec "$project_yml" 2>&1; then
        log_warn "[xcodegen] Failed to generate project from $project_yml (may need pod install first)"
        FAILED_PROJECTS+=("$project_yml")
    fi
done

# Step 2: Generate MSPDemoApp project.yml (if in Pods mode)
if [[ "$TARGET_MODE" == "pods" ]] && [[ -f "$PROJECT_SPEC" ]]; then
    log_info "[xcodegen] Generating MSPDemoApp project"
    if ! xcodegen generate --spec "$PROJECT_SPEC" 2>&1; then
        log_warn "[xcodegen] Failed to generate MSPDemoApp project (may need pod install first)"
        FAILED_PROJECTS+=("$PROJECT_SPEC")
    fi
fi

if [[ ${#FAILED_PROJECTS[@]} -gt 0 ]]; then
    log_warn "[xcodegen] ${#FAILED_PROJECTS[@]} project(s) failed to generate (will be generated after pod install)"
fi

# Step 3: Create the .xcworkspace file manually from workspace.yml
log_step "Creating .xcworkspace file"
WORKSPACE_PATH="$ROOT_DIR/.generated/msp-ios-sdk.xcworkspace"
WORKSPACE_DATA="$WORKSPACE_PATH/contents.xcworkspacedata"
mkdir -p "$WORKSPACE_PATH"

# Extract project paths from workspace.yml
PROJECT_PATHS=()
while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]*path:[[:space:]]*(.+)$ ]]; then
        project_path="${BASH_REMATCH[1]}"
        PROJECT_PATHS+=("$project_path")
    fi
done < <(grep -E "^[[:space:]]*path:" "$WORKSPACE_SPEC" || true)

# Generate workspace XML
{
    cat <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
XML
    
    for project_path in "${PROJECT_PATHS[@]}"; do
        if [[ "$project_path" == *.xcodeproj ]]; then
            # Direct .xcodeproj reference
            cat <<XML
   <FileRef
      location = "group:${project_path}">
   </FileRef>
XML
        elif [[ "$project_path" == *.yml ]]; then
            # YAML spec - reference the generated .xcodeproj
            project_dir="$(dirname "$project_path")"
            project_name="$(basename "$project_dir")"
            xcodeproj_path="${project_dir}/${project_name}.xcodeproj"
            cat <<XML
   <FileRef
      location = "group:${xcodeproj_path}">
   </FileRef>
XML
        fi
    done
    
    echo "</Workspace>"
} > "$WORKSPACE_DATA"

log_success "[xcodegen] Successfully generated .xcworkspace"

log_title "YAML Generation Complete"
log_success "YAML specs generated for $TARGET_MODE mode"
