#!/usr/bin/env bash
# ============================================================================
# Workspace Generation
# ============================================================================
# Purpose: Generate workspace and project specs based on current mode (SPM or Pods)
#
# Usage:   ./Scripts/target-switching/generate_workspace.sh [spm|pods]
# ============================================================================

set -euo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=Scripts/target-switching/common.sh
source "$SCRIPT_DIR/common.sh"

ensure_repo_root

TARGET_MODE="${1:-}"
if [[ -z "$TARGET_MODE" ]]; then
    # Auto-detect mode
    TARGET_MODE=$(detect_current_mode)
    if [[ "$TARGET_MODE" == "mixed" ]]; then
        log_error "Cannot auto-detect mode (mixed environment detected)"
        log_info "Please specify: $0 [spm|pods]"
        exit 1
    fi
fi

if [[ "$TARGET_MODE" != "spm" ]] && [[ "$TARGET_MODE" != "pods" ]]; then
    log_error "Invalid mode. Must be 'spm' or 'pods'"
    exit 1
fi

echo "============================================================================"
echo "Generating Workspace: $TARGET_MODE mode"
echo "============================================================================"
echo ""

# Source the original update script's logic
UPDATE_SCRIPT="$ROOT_DIR/Scripts/workspace/update.sh"
if [[ ! -f "$UPDATE_SCRIPT" ]]; then
    log_error "Workspace update script not found: $UPDATE_SCRIPT"
    exit 1
fi

# Find all Package.swift files
PACKAGE_FILES=()
while IFS= read -r pkg_file; do
    PACKAGE_FILES+=("$pkg_file")
done < <(find "$ROOT_DIR" -name Package.swift \
    ! -path '*/Pods/*' ! -path '*/DerivedData/*' ! -path '*/.build/*' \
    -print | LC_ALL=C sort)

PACKAGE_NAMES=()
PACKAGE_REL_PATHS=()
for pkg in "${PACKAGE_FILES[@]}"; do
    pkg_dir="${pkg%/Package.swift}"
    pkg_name="$(basename "$pkg_dir")"
    rel_path="${pkg_dir#$ROOT_DIR/}"
    PACKAGE_NAMES+=("$pkg_name")
    PACKAGE_REL_PATHS+=("$rel_path")
done

# SPM app products
declare -a SPM_APP_PRODUCTS=(
    "MSPCore"
    "NovaAdapter"
    "PrebidAdapter"
    "MSPGoogleAdapter"
    "MSPFacebookAdapter"
    "MSPSharedLibraries"
    "MSPOMSDK"
    "MSPiOSCore"
    "NovaCore"
    "ShimmerWrapper"
    "FBAudienceNetworkWrapper"
    "IronSourceSDKWrapper"
    "OpenWrapSDKWrapper"
    "MintegralAdSDKWrapper"
    "MobileFuseSDKWrapper"
    "InMobiSDKWrapper"
    "UnityAdapter"
    "PubmaticAdapter"
    "MintegralAdapter"
    "MobilefuseAdapter"
    "InmobiAdapter"
)

package_exists() {
    local name="$1"
    for candidate in "${PACKAGE_NAMES[@]}"; do
        if [[ "$candidate" == "$name" ]]; then
            return 0
        fi
    done
    return 1
}

# Generate project.yml (overwrite, don't append)
log_step "1" "Generating project.yml"
mkdir -p "$(dirname "$PROJECT_SPEC")"

# Ensure we start with a clean file
> "$PROJECT_SPEC"

{
    cat <<'YAML'
# This file is auto-generated by Scripts/target-switching/generate_workspace.sh
name: MSPDemoApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "15.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    DEVELOPMENT_TEAM: 4PEHUZX8QH
    PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoApp
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.0.117
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    INFOPLIST_FILE: MSPDemoApp/Info.plist
YAML

    # Add packages section
    if [[ ${#PACKAGE_NAMES[@]} -eq 0 ]]; then
        echo "packages: {}"
    else
        echo "packages:"
        for ((i=0; i<${#PACKAGE_NAMES[@]}; i++)); do
            raw_name="${PACKAGE_NAMES[$i]}"
            rel="../${PACKAGE_REL_PATHS[$i]}"
            cat <<YAML
  ${raw_name}:
    name: ${raw_name}
    path: ${rel}
YAML
        done
    fi

    cat <<'YAML'
targetTemplates:
  BaseAppTarget:
    type: application
    platform: iOS
    sources:
      - path: MSPDemoApp
    info:
      path: MSPDemoApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: 5.0
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
targets:
YAML

    # MSPDemoApp target (CocoaPods only)
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
  MSPDemoApp:
    templates:
      - BaseAppTarget
    settings:
      base:
        PODS_ROOT: "$(SRCROOT)/../Pods"
    configFiles:
      Debug: ../Pods/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp.debug.xcconfig
      Release: ../Pods/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp.release.xcconfig
    prebuildScripts:
      - name: "[CP] Check Pods Manifest.lock"
        script: |
          if [ -z "${PODS_PODFILE_DIR_PATH}" ] || [ -z "${PODS_ROOT}" ]; then
            echo "error: CocoaPods environment variables are not set." >&2
            exit 1
          fi
          if [ ! -e "${PODS_ROOT}/Manifest.lock" ] || [ ! -e "${PODS_PODFILE_DIR_PATH}/Podfile.lock" ]; then
            echo "error: Run 'pod install' to generate Pods/Manifest.lock." >&2
            exit 1
          fi
          if ! diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" >/dev/null; then
            echo "error: Podfile.lock and Manifest.lock are out of sync. Run 'pod install'." >&2
            exit 1
          fi
        shell: /bin/sh
    postbuildScripts:
      - name: "[CP] Embed Pods Frameworks"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-frameworks.sh\""
        shell: /bin/sh
      - name: "[CP] Copy Pods Resources"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-resources.sh\""
        shell: /bin/sh
YAML
    fi

    # MSPDemoApp-SPM target (SPM only)
    if [[ "$TARGET_MODE" == "spm" ]]; then
        cat <<'YAML'
  MSPDemoApp-SPM:
    templates:
      - BaseAppTarget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoAppSPM
    configFiles:
      Debug: ../Configs/MSPDemoApp-Debug-SPM.xcconfig
      Release: ../Configs/MSPDemoApp-Release-SPM.xcconfig
    dependencies:
YAML
        for product in "${SPM_APP_PRODUCTS[@]}"; do
            if package_exists "$product"; then
                cat <<YAML
      - package: ${product}
        product: ${product}
YAML
            fi
        done
    fi

    # Test targets (only for Pods mode)
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
  MSPDemoAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MSPDemoAppTests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MSPDemoApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MSPDemoApp"
    dependencies:
      - target: MSPDemoApp
  MSPDemoAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MSPDemoAppUITests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - target: MSPDemoApp
YAML
    fi

    # Schemes
    cat <<'YAML'
schemes:
YAML
    if [[ "$TARGET_MODE" == "pods" ]]; then
        cat <<'YAML'
  MSPDemoApp:
    build:
      targets:
        MSPDemoApp: all
        MSPDemoAppTests: test
        MSPDemoAppUITests: test
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - target: MSPDemoAppTests
        - target: MSPDemoAppUITests
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
YAML
    else
        cat <<'YAML'
  MSPDemoApp-SPM:
    build:
      targets:
        MSPDemoApp-SPM: all
    test:
      config: Debug
      targets: []
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
YAML
    fi
} > "$PROJECT_SPEC"

log_success "project.yml generated"

# Generate workspace.yml (for xcodegen reference, not used in CocoaPods mode)
log_step "2" "Generating workspace.yml"

# Find all .xcodeproj files (excluding Pods and build artifacts)
# In SPM mode, exclude ALL Pods projects; in Pods mode, include them
PROJECTS=()
if [[ "$TARGET_MODE" == "spm" ]]; then
    # SPM mode: exclude all Pods projects
    while IFS= read -r proj; do
        PROJECTS+=("$proj")
    done < <(find "$ROOT_DIR" -name '*.xcodeproj' \
        ! -path '*/DerivedData/*' ! -path '*/Pods/*' \
        -print | LC_ALL=C sort)
else
    # Pods mode: exclude only Pods/Pods.xcodeproj internals, but include individual pod projects
    while IFS= read -r proj; do
        PROJECTS+=("$proj")
    done < <(find "$ROOT_DIR" -name '*.xcodeproj' \
        ! -path '*/DerivedData/*' ! -path '*/Pods/Pods.xcodeproj/*' \
        -print | LC_ALL=C sort)
fi

{
    echo "workspace:"
    echo "  name: msp-ios-sdk"
    echo "  projects:"
    echo "    - name: MSPDemoApp"
    echo "      path: MSPDemoApp/project.yml"
    echo "      type: file"
    
    # Add all found projects (excluding generated MSPDemoApp)
    for proj in "${PROJECTS[@]}"; do
        rel="${proj#$ROOT_DIR/}"
        if [[ "$rel" == "MSPDemoApp/MSPDemoApp.xcodeproj" ]]; then
            continue
        fi
        project_name="$(basename "${rel%.*}")"
        echo "    - name: ${project_name}"
        echo "      path: ${rel}"
        echo "      type: file"
    done
    
    # Only include Pods project if in Pods mode AND it exists
    # Note: Individual pod projects are already included via the find command above
    if [[ "$TARGET_MODE" == "pods" ]] && [[ -d "$PODS_DIR/Pods.xcodeproj" ]]; then
        echo "    - name: Pods"
        echo "      path: Pods/Pods.xcodeproj"
        echo "      type: file"
    fi
} > "$WORKSPACE_SPEC"

log_success "workspace.yml generated (reference only for CocoaPods mode)"

# Generate workspace contents (SPM mode only)
# Note: CocoaPods mode uses MSPDemoApp.xcworkspace created by pod install
if [[ "$TARGET_MODE" == "spm" ]]; then
    log_step "3" "Generating SPM workspace contents"
    mkdir -p "$SPM_WORKSPACE"
    SWIFTPM_DIR="$SPM_WORKSPACE/xcshareddata/swiftpm"
    SWIFTPM_JSON="$SWIFTPM_DIR/local-packages.json"
    mkdir -p "$SWIFTPM_DIR"
    
    # Write SwiftPM package manifest
    {
        echo "["
        for ((i=0; i<${#PACKAGE_NAMES[@]}; i++)); do
            name="${PACKAGE_NAMES[$i]}"
            rel="${PACKAGE_REL_PATHS[$i]}"
            suffix=","
            if [[ $i -eq $((${#PACKAGE_NAMES[@]} - 1)) ]]; then
                suffix=""
            fi
            printf '  {"name":"%s","path":"%s"}%s\n' "$name" "$rel" "$suffix"
        done
        echo "]"
    } > "$SWIFTPM_JSON"
    
    # Generate workspace XML
    WORKSPACE_DATA="$SPM_WORKSPACE/contents.xcworkspacedata"
    {
        cat <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
      location = "group:MSPDemoApp/MSPDemoApp.xcodeproj">
   </FileRef>
XML
        for proj in "${PROJECTS[@]}"; do
            rel="${proj#$ROOT_DIR/}"
            if [[ "$rel" == "MSPDemoApp/MSPDemoApp.xcodeproj" ]]; then
                continue
            fi
            # In SPM mode, exclude all Pods projects
            if [[ "$TARGET_MODE" == "spm" ]] && [[ "$rel" == Pods/* ]]; then
                continue
            fi
            cat <<XML
   <FileRef
      location = "group:${rel}">
   </FileRef>
XML
        done
        # Only include Pods/Pods.xcodeproj in Pods mode
        if [[ "$TARGET_MODE" == "pods" ]] && [[ -d "$PODS_DIR/Pods.xcodeproj" ]]; then
            cat <<'XML'
   <FileRef
      location = "group:Pods/Pods.xcodeproj">
   </FileRef>
XML
        fi
        echo "</Workspace>"
    } > "$WORKSPACE_DATA"
    
    log_success "SPM workspace contents generated"
else
    log_step "3" "Skipping SPM workspace generation (CocoaPods mode)"
    log_info "CocoaPods workspace (MSPDemoApp.xcworkspace) will be created by pod install"
fi

# Run xcodegen
log_step "4" "Running xcodegen"
XCODEGEN_BIN="$(command -v xcodegen || true)"
if [[ -z "$XCODEGEN_BIN" ]]; then
    log_warning "xcodegen is not installed. Install via 'brew install xcodegen' (2.38.0+ required)"
else
    if "$XCODEGEN_BIN" generate --spec "$PROJECT_SPEC"; then
        log_success "xcodegen completed"
    else
        log_error "xcodegen failed. Ensure version 2.38.0+ is installed (run 'brew upgrade xcodegen')."
        exit 1
    fi
fi

echo ""
echo "============================================================================"
echo "Workspace Generation Complete"
echo "============================================================================"
echo ""
log_success "Workspace generated for $TARGET_MODE mode"

