#!/usr/bin/env bash
set -euo pipefail

# ============================================
# Test Case: A1_dry_off_strict_off_no_url
# Auto-generated by generate_cases.sh
# ============================================

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

# Load UI system
source "$SCRIPT_ROOT/Scripts/lib/release-common.sh"

export DRY_RUN="0"
export VERIFY_SPM_STRICT="0"
export SPM_REMOTE_URL=""

# pods-only / spm-only overrides
if [[ "A1_dry_off_strict_off_no_url" == "E2_pods_only" ]]; then
    export SKIP_SPM=1
elif [[ "A1_dry_off_strict_off_no_url" == "E3_spm_only" ]]; then
    export SKIP_PODS=1
fi

echo "[CASE] Running: A1_dry_off_strict_off_no_url"
echo "  DRY_RUN=0"
echo "  VERIFY_SPM_STRICT=0"
echo "  SPM_REMOTE_URL=''"

# Call main verify command
"$SCRIPT_ROOT"/Scripts/msp-release.sh verify "0.0.0-test"
