#!/usr/bin/env bash
set -euo pipefail

# ============================================
# Test Case: C3_dry_on_strict_off_invalid_url
# Auto-generated by generate_cases.sh
# ============================================

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

# Load UI system
source "$SCRIPT_ROOT/Scripts/lib/release-common.sh"

export DRY_RUN="1"
export VERIFY_SPM_STRICT="0"
export SPM_REMOTE_URL="https://invalid.url/repo.git"

# pods-only / spm-only overrides
if [[ "C3_dry_on_strict_off_invalid_url" == "E2_pods_only" ]]; then
    export SKIP_SPM=1
elif [[ "C3_dry_on_strict_off_invalid_url" == "E3_spm_only" ]]; then
    export SKIP_PODS=1
fi

echo "[CASE] Running: C3_dry_on_strict_off_invalid_url"
echo "  DRY_RUN=1"
echo "  VERIFY_SPM_STRICT=0"
echo "  SPM_REMOTE_URL='https://invalid.url/repo.git'"

# Call main verify command
"$SCRIPT_ROOT"/Scripts/msp-release.sh verify "0.0.0-test"
