#!/usr/bin/env bash
# --- MSP Worktree Safety Guard (Patch K, shared) ---
# shellcheck source=/dev/null
if command -v git >/dev/null 2>&1; then
  MSP_REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  if [ -n "$MSP_REPO_ROOT" ] && [ -f "$MSP_REPO_ROOT/Scripts/lib/worktree_guard.sh" ]; then
    # shellcheck source=/dev/null
    . "$MSP_REPO_ROOT/Scripts/lib/worktree_guard.sh"
    msp_enforce_main_repo_or_exit
  fi
fi
# --- End MSP Worktree Safety Guard (Patch K, shared) ---
set -euo pipefail

# ============================================
# Test Case: D2_dry_on_strict_on_valid_url
# Auto-generated by generate_cases.sh
# ============================================

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

# Load UI system
source "$SCRIPT_ROOT/Scripts/lib/release-common.sh"

export DRY_RUN="1"
export VERIFY_SPM_STRICT="1"
export SPM_REMOTE_URL="https://github.com/ParticleMedia/msp-ios-sdk-public"

# pods-only / spm-only overrides
if [[ "D2_dry_on_strict_on_valid_url" == "E2_pods_only" ]]; then
    export SKIP_SPM=1
elif [[ "D2_dry_on_strict_on_valid_url" == "E3_spm_only" ]]; then
    export SKIP_PODS=1
fi

echo "[CASE] Running: D2_dry_on_strict_on_valid_url"
echo "  DRY_RUN=1"
echo "  VERIFY_SPM_STRICT=1"
echo "  SPM_REMOTE_URL='https://github.com/ParticleMedia/msp-ios-sdk-public'"

# Call main verify command
"$SCRIPT_ROOT"/Scripts/msp-release.sh verify "0.0.0-test"
