#!/usr/bin/env bash
# --- MSP Worktree Safety Guard (Patch M, shared) ---
# shellcheck source=/dev/null
_msp_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$_msp_root" ] && [ -f "$_msp_root/Scripts/lib/worktree_guard.sh" ]; then
  . "$_msp_root/Scripts/lib/worktree_guard.sh"
  msp_enforce_main_repo_or_exit
fi
unset _msp_root
# --- End MSP Worktree Safety Guard (Patch M, shared) ---
set -euo pipefail

# ============================================
# Test Case: E3_spm_only
# Auto-generated by generate_cases.sh
# ============================================

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

# Load UI system
source "$SCRIPT_ROOT/Scripts/lib/release-common.sh"

export DRY_RUN="0"
export VERIFY_SPM_STRICT="1"
export SPM_REMOTE_URL="https://github.com/ParticleMedia/msp-ios-sdk-public"

# pods-only / spm-only overrides
if [[ "E3_spm_only" == "E2_pods_only" ]]; then
    export SKIP_SPM=1
elif [[ "E3_spm_only" == "E3_spm_only" ]]; then
    export SKIP_PODS=1
fi

echo "[CASE] Running: E3_spm_only"
echo "  DRY_RUN=0"
echo "  VERIFY_SPM_STRICT=1"
echo "  SPM_REMOTE_URL='https://github.com/ParticleMedia/msp-ios-sdk-public'"

# Call main verify command
"$SCRIPT_ROOT"/Scripts/msp-release.sh verify "0.0.0-test"
