//
//  UIImage.swift
//  Pods
//
//  Created by Wei Wu (iOS) on 11/7/23.
//
import UIKit
import Foundation
/*
public extension UIImage {
    func tint(_ tintColor: UIColor) -> UIImage {
        UIImage(image: self, tintColor: tintColor) ?? self
    }
}

extension UIImage {
    @objc convenience init?(image: UIImage, tintColor: UIColor) {
        func iconCgImage(for userInterfaceStyle: UIUserInterfaceStyle) -> CGImage? {
            var iconColor = tintColor
            iconColor = tintColor.resolvedColor(with: UITraitCollection(userInterfaceStyle: userInterfaceStyle))
            
            let iconRender = UIGraphicsImageRenderer(
                size: CGSize(width: image.size.width, height: image.size.height)
            )
            
            let iconImage = iconRender.image { context in
                let bounds = context.format.bounds
                iconColor.setFill()
                context.fill(bounds)
                image.draw(in: bounds, blendMode: .destinationIn, alpha: 1.0)
            }
            
            return iconImage.cgImage
        }
        
        guard let lightCgImage = iconCgImage(for: .light), let darkCgImage = iconCgImage(for: .dark) else { return nil }
        
        self.init(cgImage: lightCgImage, scale: image.scale, orientation: image.imageOrientation)
        
        let darkImage = UIImage(cgImage: darkCgImage, scale: image.scale, orientation: image.imageOrientation)
        let traitCollection = UITraitCollection(traitsFrom: [
            UITraitCollection(displayScale: UITraitCollection.current.displayScale),
            UITraitCollection(userInterfaceStyle: .dark),
        ])
        self.imageNovaAsset?.register(darkImage, with: traitCollection)
    }
}
*/
public extension UIImage {
    static let Nova = NovaImage()
    
    class NovaImage {
        public let aiSummaryFilled = UIImage(named: "ai_summary_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let aiSummaryLine = UIImage(named: "ai_summary_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let alertFilled = UIImage(named: "alert_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let alertLine = UIImage(named: "alert_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowClockwiseFilled = UIImage(named: "arrow_clockwise_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowClockwiseLine = UIImage(named: "arrow_clockwise_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowCounterclockwiseFilled = UIImage(named: "arrow_counterclockwise_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowCounterclockwiseLine = UIImage(named: "arrow_counterclockwise_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowDownFilled = UIImage(named: "arrow_down_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowDownLine = UIImage(named: "arrow_down_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowLeftFilled = UIImage(named: "arrow_left_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowLeftLine = UIImage(named: "arrow_left_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowLineUpFilled = UIImage(named: "arrow_line_up_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowLineUpLine = UIImage(named: "arrow_line_up_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowLineUpOffFilled = UIImage(named: "arrow_line_up_off_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowLineUpOffLine = UIImage(named: "arrow_line_up_off_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowRightFilled = UIImage(named: "arrow_right_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowRightLine = UIImage(named: "arrow_right_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowTipDownFilled = UIImage(named: "arrow_tip_down_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowTipDownLine = UIImage(named: "arrow_tip_down_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowTipUpFilled = UIImage(named: "arrow_tip_up_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowTipUpLine = UIImage(named: "arrow_tip_up_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowUpFilled = UIImage(named: "arrow_up_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let arrowUpLine = UIImage(named: "arrow_up_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let backwordAudioFilled = UIImage(named: "backword_audio_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let backwordAudioLine = UIImage(named: "backword_audio_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let bellFilled = UIImage(named: "bell_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let bellLine = UIImage(named: "bell_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let bookmarkFilled = UIImage(named: "bookmark_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let bookmarkLine = UIImage(named: "bookmark_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let bookmarkPageFilled = UIImage(named: "bookmark_page_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let bookmarkPageLine = UIImage(named: "bookmark_page_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let calendarFilled = UIImage(named: "calendar_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let calendarLine = UIImage(named: "calendar_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let callFilled = UIImage(named: "call_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let callLine = UIImage(named: "call_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cameraFilled = UIImage(named: "camera_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cameraLine = UIImage(named: "camera_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cameraSwitchFilled = UIImage(named: "camera_switch_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cameraSwitchLine = UIImage(named: "camera_switch_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let categoryFilled = UIImage(named: "category_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let categoryLine = UIImage(named: "category_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chartBarFilled = UIImage(named: "chart_bar_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chartBarLine = UIImage(named: "chart_bar_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chartUpFilled = UIImage(named: "chart_up_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chartUpLine = UIImage(named: "chart_up_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chatFilled = UIImage(named: "chat_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chatInfoFilled = UIImage(named: "chat_info_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chatInfoLine = UIImage(named: "chat_info_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chatLine = UIImage(named: "chat_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let checkmarkCircleFilled = UIImage(named: "checkmark_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let checkmarkCircleLine = UIImage(named: "checkmark_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let checkmarkFilled = UIImage(named: "checkmark_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let checkmarkLine = UIImage(named: "checkmark_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronDownCircleFilled = UIImage(named: "chevron_down_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronDownCircleLine = UIImage(named: "chevron_down_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronDownFilled = UIImage(named: "chevron_down_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronDownLine = UIImage(named: "chevron_down_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronLeftCircleFilled = UIImage(named: "chevron_left_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronLeftCircleLine = UIImage(named: "chevron_left_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronLeftFilled = UIImage(named: "chevron_left_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronLeftLine = UIImage(named: "chevron_left_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronRightCircleFilled = UIImage(named: "chevron_right_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronRightCircleLine = UIImage(named: "chevron_right_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronRightFilled = UIImage(named: "chevron_right_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronRightLine = UIImage(named: "chevron_right_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronUpCircleFilled = UIImage(named: "chevron_up_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronUpCircleLine = UIImage(named: "chevron_up_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronUpFilled = UIImage(named: "chevron_up_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let chevronUpLine = UIImage(named: "chevron_up_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let clockFilled = UIImage(named: "clock_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let clockLeftFilled = UIImage(named: "clock_left_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let clockLeftLine = UIImage(named: "clock_left_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let clockLine = UIImage(named: "clock_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cloudFilled = UIImage(named: "cloud_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cloudLine = UIImage(named: "cloud_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let coffeeFilled = UIImage(named: "coffee_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let coffeeLine = UIImage(named: "coffee_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let compassFilled = UIImage(named: "compass_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let compassLine = UIImage(named: "compass_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let composeFilled = UIImage(named: "compose_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let composeLine = UIImage(named: "compose_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let contextFilled = UIImage(named: "context_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let contextFilledFilled = UIImage(named: "context_filled_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let contextFilledLine = UIImage(named: "context_filled_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let contextLine = UIImage(named: "context_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let conversationFilled = UIImage(named: "conversation_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let conversationLine = UIImage(named: "conversation_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cornerInFilled = UIImage(named: "corner_in_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cornerInLine = UIImage(named: "corner_in_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cornerOutFilled = UIImage(named: "corner_out_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let cornerOutLine = UIImage(named: "corner_out_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let crossCircleFilled = UIImage(named: "cross_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let crossCircleLine = UIImage(named: "cross_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let crossFilled = UIImage(named: "cross_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let crossLine = UIImage(named: "cross_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let desktopFilled = UIImage(named: "desktop_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let desktopLine = UIImage(named: "desktop_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let directionFilled = UIImage(named: "direction_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let directionLine = UIImage(named: "direction_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let displayFilled = UIImage(named: "display_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let displayLine = UIImage(named: "display_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let downloadFilled = UIImage(named: "download_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let downloadLine = UIImage(named: "download_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let earpodFilled = UIImage(named: "earpod_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let earpodLine = UIImage(named: "earpod_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let ellipsisHorizontalCircleFilled = UIImage(named: "ellipsis_horizontal_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let ellipsisHorizontalCircleLine = UIImage(named: "ellipsis_horizontal_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let ellipsisHorizontalFilled = UIImage(named: "ellipsis_horizontal_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let ellipsisHorizontalLine = UIImage(named: "ellipsis_horizontal_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let ellipsisVerticalCircleFilled = UIImage(named: "ellipsis_vertical_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let ellipsisVerticalCircleLine = UIImage(named: "ellipsis_vertical_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let ellipsisVerticalFilled = UIImage(named: "ellipsis_vertical_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let ellipsisVerticalLine = UIImage(named: "ellipsis_vertical_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let errorFilled = UIImage(named: "error_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let errorLine = UIImage(named: "error_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let fastForwardFilled = UIImage(named: "fast_forward_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let fastForwardLine = UIImage(named: "fast_forward_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let filter2Filled = UIImage(named: "filter2_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let filter2Line = UIImage(named: "filter2_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let filterFilled = UIImage(named: "filter_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let filterLine = UIImage(named: "filter_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let fireFilled = UIImage(named: "fire_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let fireLine = UIImage(named: "fire_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let flagFilled = UIImage(named: "flag_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let flagLine = UIImage(named: "flag_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let forwordAudioFilled = UIImage(named: "forword_audio_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let forwordAudioLine = UIImage(named: "forword_audio_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let giftFilled = UIImage(named: "gift_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let giftLine = UIImage(named: "gift_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let globalFilled = UIImage(named: "global_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let globalLine = UIImage(named: "global_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let handFilled = UIImage(named: "hand_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let handLine = UIImage(named: "hand_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let handleFilled = UIImage(named: "handle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let handleLine = UIImage(named: "handle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let hashtagFilled = UIImage(named: "hashtag_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let hashtagLine = UIImage(named: "hashtag_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let heartFilled = UIImage(named: "heart_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let heartLine = UIImage(named: "heart_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let hideFilled = UIImage(named: "hide_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let hideLine = UIImage(named: "hide_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let homeFilled = UIImage(named: "home_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let homeLine = UIImage(named: "home_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let imageFilled = UIImage(named: "image_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let imageLine = UIImage(named: "image_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let infoFilled = UIImage(named: "info_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let infoLine = UIImage(named: "info_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let inviteFilled = UIImage(named: "invite_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let inviteLine = UIImage(named: "invite_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let keyFilled = UIImage(named: "key_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let keyLine = UIImage(named: "key_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let kudosFilled = UIImage(named: "kudos_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let kudosLine = UIImage(named: "kudos_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let layerFilled = UIImage(named: "layer_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let layerLine = UIImage(named: "layer_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lightbulbFilled = UIImage(named: "lightbulb_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lightbulbInfoFilled = UIImage(named: "lightbulb_info_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lightbulbInfoLine = UIImage(named: "lightbulb_info_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lightbulbLine = UIImage(named: "lightbulb_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lightbulbfilled1 = UIImage(named: "lightbulbfilled_1", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lightbulbline1 = UIImage(named: "lightbulbline_1", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lightningFilled = UIImage(named: "lightning_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lightningLine = UIImage(named: "lightning_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let linkFilled = UIImage(named: "link_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let linkLine = UIImage(named: "link_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let listBulletFilled = UIImage(named: "list_bullet_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let listBulletLine = UIImage(named: "list_bullet_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let locationFilled = UIImage(named: "location_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let locationLine = UIImage(named: "location_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lockFilled = UIImage(named: "lock_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let lockLine = UIImage(named: "lock_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let loginFilled = UIImage(named: "login_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let loginLine = UIImage(named: "login_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let logoutFilled = UIImage(named: "logout_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let logoutLine = UIImage(named: "logout_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let magicFilled = UIImage(named: "magic_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let magicLine = UIImage(named: "magic_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let mailFilled = UIImage(named: "mail_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let mailLine = UIImage(named: "mail_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let mailboxFilled = UIImage(named: "mailbox_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let mailboxLine = UIImage(named: "mailbox_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let mapFilled = UIImage(named: "map_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let mapLine = UIImage(named: "map_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let micFilled = UIImage(named: "mic_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let micLine = UIImage(named: "mic_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let minusCircleFilled = UIImage(named: "minus_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let minusCircleLine = UIImage(named: "minus_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let minusFilled = UIImage(named: "minus_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let minusLine = UIImage(named: "minus_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let mobileFilled = UIImage(named: "mobile_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let mobileLine = UIImage(named: "mobile_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let moneyFilled = UIImage(named: "money_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let moneyLine = UIImage(named: "money_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let moonFilled = UIImage(named: "moon_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let moonLine = UIImage(named: "moon_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let musicFilled = UIImage(named: "music_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let musicLine = UIImage(named: "music_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let musicWaveFilled = UIImage(named: "music_wave_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let musicWaveLine = UIImage(named: "music_wave_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let muteFilled = UIImage(named: "mute_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let muteLine = UIImage(named: "mute_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let navigationFilled = UIImage(named: "navigation_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let navigationLine = UIImage(named: "navigation_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let newChatFilled = UIImage(named: "new_chat_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let newChatLine = UIImage(named: "new_chat_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let newsbreakFilled = UIImage(named: "newsbreak_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let newsbreakLine = UIImage(named: "newsbreak_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let newspaperFilled = UIImage(named: "newspaper_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let newspaperLine = UIImage(named: "newspaper_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let nextSongFilled = UIImage(named: "next_song_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let nextSongLine = UIImage(named: "next_song_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let pauseAudioFilled = UIImage(named: "pause_audio_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let pauseAudioLine = UIImage(named: "pause_audio_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let pauseFilled = UIImage(named: "pause_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let pauseLine = UIImage(named: "pause_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let pencilFilled = UIImage(named: "pencil_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let pencilLine = UIImage(named: "pencil_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let peopleFilled = UIImage(named: "people_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let peopleLine = UIImage(named: "people_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let pinFilled = UIImage(named: "pin_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let pinLine = UIImage(named: "pin_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let playAudioFilled = UIImage(named: "play_audio_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let playAudioLine = UIImage(named: "play_audio_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let playFilled = UIImage(named: "play_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let playLine = UIImage(named: "play_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let plusCircleFilled = UIImage(named: "plus_circle_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let plusCircleLine = UIImage(named: "plus_circle_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let playFilledNew = UIImage(named: "video_pause", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let plusFilled = UIImage(named: "plus_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let plusLine = UIImage(named: "plus_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let plusSquareFilled = UIImage(named: "plus_square_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let plusSquareLine = UIImage(named: "plus_square_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let podcastsFilled = UIImage(named: "podcasts_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let podcastsLine = UIImage(named: "podcasts_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let policeDepartmentFilled = UIImage(named: "police_department_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let policeDepartmentLine = UIImage(named: "police_department_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let preSongFilled = UIImage(named: "pre_song_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let preSongLine = UIImage(named: "pre_song_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let profileFilled = UIImage(named: "profile_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let profileLine = UIImage(named: "profile_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let questionFilled = UIImage(named: "question_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let questionLine = UIImage(named: "question_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let recordFilled = UIImage(named: "record_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let recordLine = UIImage(named: "record_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let refreshFilled = UIImage(named: "refresh_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let refreshLine = UIImage(named: "refresh_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let repostFilled = UIImage(named: "repost_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let repostLine = UIImage(named: "repost_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let revealFilled = UIImage(named: "reveal_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let revealLine = UIImage(named: "reveal_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let rewindFilled = UIImage(named: "rewind_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let rewindLine = UIImage(named: "rewind_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let sadFilled = UIImage(named: "sad_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let sadLine = UIImage(named: "sad_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let screenshotFilled = UIImage(named: "screenshot_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let screenshotLine = UIImage(named: "screenshot_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let searchFilled = UIImage(named: "search_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let searchLine = UIImage(named: "search_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let sendFilled = UIImage(named: "send_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let sendLine = UIImage(named: "send_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let settingFilled = UIImage(named: "setting_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let settingLine = UIImage(named: "setting_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let shareAndroidFilled = UIImage(named: "share_android_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let shareAndroidLine = UIImage(named: "share_android_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let shareFilled = UIImage(named: "share_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let shareLine = UIImage(named: "share_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let shortpostFilled = UIImage(named: "shortpost_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let shortpostLine = UIImage(named: "shortpost_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let smileyFilled = UIImage(named: "smiley_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let smileyLine = UIImage(named: "smiley_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let starFilled = UIImage(named: "star_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let starLine = UIImage(named: "star_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let stopFilled = UIImage(named: "stop_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let stopLine = UIImage(named: "stop_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let switchFilled = UIImage(named: "switch_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let switchLine = UIImage(named: "switch_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let targetFilled = UIImage(named: "target_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let targetLine = UIImage(named: "target_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let textSizeFilled = UIImage(named: "text_size_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let textSizeLine = UIImage(named: "text_size_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let thumbsDownFilled = UIImage(named: "thumbs_down_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let thumbsDownLine = UIImage(named: "thumbs_down_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let thumbsUpFilled = UIImage(named: "thumbs_up_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let thumbsUpLine = UIImage(named: "thumbs_up_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let titleFilled = UIImage(named: "title_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let titleLine = UIImage(named: "title_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let translationFilled = UIImage(named: "translation_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let translationLine = UIImage(named: "translation_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let trashFilled = UIImage(named: "trash_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let trashLine = UIImage(named: "trash_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let trendDownFilled = UIImage(named: "trend_down_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let trendDownLine = UIImage(named: "trend_down_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let trendUpFilled = UIImage(named: "trend_up_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let trendUpLine = UIImage(named: "trend_up_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let unlockFilled = UIImage(named: "unlock_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let unlockLine = UIImage(named: "unlock_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let unpinFilled = UIImage(named: "unpin_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let uppinLine = UIImage(named: "uppin_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let videoClipFilled = UIImage(named: "video_clip_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let videoClipLine = UIImage(named: "video_clip_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let videoFilled = UIImage(named: "video_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let videoLine = UIImage(named: "video_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let volumeOffFilled = UIImage(named: "volume_off_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let volumeOffLine = UIImage(named: "volume_off_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let volumeOnFilled = UIImage(named: "volume_on_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let volumeOnLine = UIImage(named: "volume_on_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let volumeUpFilled = UIImage(named: "volume_up_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let volumeUpLine = UIImage(named: "volume_up_line", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let volumnDownFilled = UIImage(named: "volumn_down_filled", in: NovaAsset.getBundle(), compatibleWith: nil)
        public let volumnDownLine = UIImage(named: "volumn_down_line", in: NovaAsset.getBundle(), compatibleWith: nil)
    }
}
