#!/usr/bin/env bash
# --- MSP Worktree Safety Guard (Patch L, shared) ---
# shellcheck source=/dev/null
. "$(git rev-parse --show-toplevel 2>/dev/null)/Scripts/lib/worktree_guard.sh"
msp_enforce_main_repo_or_exit
# --- End MSP Worktree Safety Guard (Patch L, shared) ---
# ============================================================================
# Patch Package.swift for Remote SPM Verification
# ============================================================================
# Purpose: Generate Package.swift to point to remote tag instead of local path
#
# Usage:   ./patch_package.swift.sh <sandbox_path> <remote_url> <remote_version> <module>
# ============================================================================

set -euo pipefail

source "$(dirname "$0")/../common/utils.sh"

# ============================================================================
# Functions
# ============================================================================

patch_package_swift() {
    local sandbox="$1"
    local remote_url="$2"
    local version="$3"
    
    if [[ -z "$sandbox" ]] || [[ -z "$remote_url" ]] || [[ -z "$version" ]]; then
        vr_log::error "SPM" "Sandbox path, remote URL, and remote version required"
        return 1
    fi
    
    # Use parsed values from parse_remote_package.sh
    local package_name="${REMOTE_PACKAGE_NAME:-}"
    local product_name="${REMOTE_PRODUCT_NAME:-}"
    
    if [[ -z "$package_name" ]] || [[ -z "$product_name" ]]; then
        vr_log::error "SPM" "REMOTE_PACKAGE_NAME and REMOTE_PRODUCT_NAME must be set (run parse_remote_package.sh first)"
        return 1
    fi
    
    # Generate Package.swift in sandbox
    cat > "$sandbox/Package.swift" <<EOF
// swift-tools-version: 5.9
// Auto-generated by verify_remote SPM
import PackageDescription

let package = Package(
    name: "DemoApp",
    platforms: [.iOS(.v14)],
    dependencies: [
        .package(url: "$remote_url", exact: "$version")
    ],
    targets: [
        .target(
            name: "DemoApp",
            dependencies: [
                .product(name: "$product_name", package: "$package_name")
            ],
            path: "DemoApp/Sources"
        )
    ]
)
EOF
    
    vr_log::info "SPM" "[SPM] Generated Package.swift:"
    vr_log::info "SPM" "  URL:           $remote_url"
    vr_log::info "SPM" "  Version:       $version"
    vr_log::info "SPM" "  Package name:  $package_name"
    vr_log::info "SPM" "  Product name:  $product_name"
    
    return 0
}

# ============================================================================
# Main
# ============================================================================

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    patch_package_swift "$@"
fi

