#!/usr/bin/env swift

// generate-stub-factory.swift
// Generates StubFactory Swift files from JSON stub data
//
// Usage:
//   swift generate-stub-factory.swift --module AdBidding --model BidResponse --input Tests/Stubs/AdBidding --output Tests/Generated
//   swift generate-stub-factory.swift --all --config stubs.yml
//
// AUTO-GENERATED files should not be manually edited.

import Foundation

// MARK: - Configuration

struct GeneratorConfig {
    let moduleName: String
    let modelName: String
    let inputDirectory: String
    let outputDirectory: String
    let stubsSubdirectory: String  // e.g., "Stubs/AdBidding"
}

// MARK: - Argument Parsing

struct Arguments {
    var moduleName: String?
    var modelName: String?
    var inputDirectory: String?
    var outputDirectory: String?
    var generateAll: Bool = false
    var configFile: String?
    var help: Bool = false

    static func parse(_ args: [String]) -> Arguments {
        var result = Arguments()
        var i = 1  // Skip program name

        while i < args.count {
            let arg = args[i]

            switch arg {
            case "--module", "-m":
                i += 1
                if i < args.count { result.moduleName = args[i] }

            case "--model", "-t":
                i += 1
                if i < args.count { result.modelName = args[i] }

            case "--input", "-i":
                i += 1
                if i < args.count { result.inputDirectory = args[i] }

            case "--output", "-o":
                i += 1
                if i < args.count { result.outputDirectory = args[i] }

            case "--all", "-a":
                result.generateAll = true

            case "--config", "-c":
                i += 1
                if i < args.count { result.configFile = args[i] }

            case "--help", "-h":
                result.help = true

            default:
                print("Unknown argument: \(arg)")
            }

            i += 1
        }

        return result
    }
}

// MARK: - File Discovery

func findJSONFiles(in directory: String) -> [String] {
    let fileManager = FileManager.default
    let directoryURL = URL(fileURLWithPath: directory)

    guard let enumerator = fileManager.enumerator(
        at: directoryURL,
        includingPropertiesForKeys: [.isRegularFileKey],
        options: [.skipsHiddenFiles]
    ) else {
        print("Error: Cannot enumerate directory \(directory)")
        return []
    }

    var jsonFiles: [String] = []

    for case let fileURL as URL in enumerator {
        if fileURL.pathExtension.lowercased() == "json" {
            let fileName = fileURL.deletingPathExtension().lastPathComponent
            jsonFiles.append(fileName)
        }
    }

    return jsonFiles.sorted()
}

// MARK: - Code Generation

func toCamelCase(_ snakeCase: String) -> String {
    let components = snakeCase.components(separatedBy: "_")
    guard let first = components.first else { return snakeCase }

    let rest = components.dropFirst().map { $0.capitalized }
    return first + rest.joined()
}

func generateScenarioEnum(from jsonFiles: [String]) -> String {
    var cases: [String] = []

    for file in jsonFiles {
        let caseName = toCamelCase(file)
        cases.append("        case \(caseName) = \"\(file)\"")
    }

    return """
        enum Scenario: String, CaseIterable {
    \(cases.joined(separator: "\n"))
        }
    """
}

func generateStubFactory(config: GeneratorConfig, jsonFiles: [String]) -> String {
    let scenarioEnum = generateScenarioEnum(from: jsonFiles)
    let lowercasedModel = config.modelName.prefix(1).lowercased() + config.modelName.dropFirst()

    return """
    // \(config.moduleName)StubFactory.swift
    // AUTO-GENERATED - DO NOT EDIT
    // Generated by: Scripts/tools/generate-stub-factory.swift
    // Generated at: \(ISO8601DateFormatter().string(from: Date()))

    import Foundation

    /// StubFactory for \(config.moduleName) module
    /// Provides test data from JSON stub files
    enum \(config.moduleName)StubFactory {

    \(scenarioEnum)

        // MARK: - Typed Access

        /// Load stub data for the given scenario
        /// - Parameter scenario: The test scenario to load
        /// - Returns: Decoded \(config.modelName) object
        static func \(lowercasedModel)(scenario: Scenario) -> \(config.modelName) {
            let data = loadJSON(scenario.rawValue)
            do {
                let decoder = JSONDecoder()
                decoder.keyDecodingStrategy = .convertFromSnakeCase
                return try decoder.decode(\(config.modelName).self, from: data)
            } catch {
                fatalError("Failed to decode \\(scenario.rawValue).json as \(config.modelName): \\(error)")
            }
        }

        // MARK: - Raw Data Access

        /// Load raw JSON data for the given scenario
        /// - Parameter scenario: The test scenario to load
        /// - Returns: Raw Data from JSON file
        static func rawData(scenario: Scenario) -> Data {
            return loadJSON(scenario.rawValue)
        }

        /// Load raw JSON string for the given scenario
        /// - Parameter scenario: The test scenario to load
        /// - Returns: JSON string from file
        static func rawString(scenario: Scenario) -> String {
            let data = loadJSON(scenario.rawValue)
            return String(data: data, encoding: .utf8) ?? ""
        }

        // MARK: - Private

        private static func loadJSON(_ name: String) -> Data {
            // Try bundle resource first (for test target)
            let bundle = Bundle(for: BundleToken.self)
            if let url = bundle.url(forResource: name, withExtension: "json", subdirectory: "\(config.stubsSubdirectory)"),
               let data = try? Data(contentsOf: url) {
                return data
            }

            // Fallback to file path (for development)
            let projectRoot = findProjectRoot()
            let filePath = "\\(projectRoot)/Tests/\(config.stubsSubdirectory)/\\(name).json"

            guard let data = FileManager.default.contents(atPath: filePath) else {
                fatalError("Missing stub file: \(config.stubsSubdirectory)/\\(name).json")
            }

            return data
        }

        private static func findProjectRoot() -> String {
            // Walk up from current file to find project root (contains Package.swift or .xcodeproj)
            var currentPath = URL(fileURLWithPath: #file)

            for _ in 0..<10 {
                currentPath = currentPath.deletingLastPathComponent()
                let packagePath = currentPath.appendingPathComponent("Package.swift")
                let xcodeProj = currentPath.appendingPathComponent("MSPCore.xcodeproj")

                if FileManager.default.fileExists(atPath: packagePath.path) ||
                   FileManager.default.fileExists(atPath: xcodeProj.path) {
                    return currentPath.path
                }
            }

            // Fallback to current directory
            return FileManager.default.currentDirectoryPath
        }
    }

    private final class BundleToken {}
    """
}

// MARK: - File Writing

func writeFile(content: String, to path: String) {
    let url = URL(fileURLWithPath: path)

    // Create directory if needed
    let directory = url.deletingLastPathComponent()
    try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

    do {
        try content.write(to: url, atomically: true, encoding: .utf8)
        print("✓ Generated: \(path)")
    } catch {
        print("✗ Error writing \(path): \(error)")
    }
}

// MARK: - Help

func printHelp() {
    print("""
    generate-stub-factory.swift

    Generates StubFactory Swift files from JSON stub data.

    USAGE:
        swift generate-stub-factory.swift --module <name> --model <type> --input <dir> --output <dir>
        swift generate-stub-factory.swift --all --config <file>

    OPTIONS:
        --module, -m <name>     Module name (e.g., AdBidding)
        --model, -t <type>      Model type name (e.g., BidResponse)
        --input, -i <dir>       Input directory containing JSON files
        --output, -o <dir>      Output directory for generated Swift file
        --all, -a               Generate for all modules defined in config
        --config, -c <file>     Config file for --all mode (default: stubs.yml)
        --help, -h              Show this help message

    EXAMPLES:
        # Generate for single module
        swift generate-stub-factory.swift \\
            --module AdBidding \\
            --model BidResponse \\
            --input Tests/Stubs/AdBidding \\
            --output Tests/Generated

        # Generate for all modules
        swift generate-stub-factory.swift --all

    JSON FILE NAMING:
        - success.json          → .success scenario
        - failure_timeout.json  → .failureTimeout scenario
        - high_bid.json         → .highBid scenario
    """)
}

// MARK: - Validation

func validateJSON(at path: String, modelName: String) -> Bool {
    guard let data = FileManager.default.contents(atPath: path) else {
        print("  ⚠ Cannot read: \(path)")
        return false
    }

    do {
        _ = try JSONSerialization.jsonObject(with: data)
        return true
    } catch {
        print("  ⚠ Invalid JSON in \(path): \(error.localizedDescription)")
        return false
    }
}

// MARK: - Main

func main() {
    let args = Arguments.parse(CommandLine.arguments)

    if args.help {
        printHelp()
        exit(0)
    }

    // Single module generation
    guard let moduleName = args.moduleName,
          let modelName = args.modelName,
          let inputDir = args.inputDirectory,
          let outputDir = args.outputDirectory else {
        print("Error: Missing required arguments")
        print("Use --help for usage information")
        exit(1)
    }

    print("Generating StubFactory for \(moduleName)...")
    print("  Input:  \(inputDir)")
    print("  Output: \(outputDir)")

    // Find JSON files
    let jsonFiles = findJSONFiles(in: inputDir)

    if jsonFiles.isEmpty {
        print("Error: No JSON files found in \(inputDir)")
        exit(1)
    }

    print("  Found \(jsonFiles.count) stub file(s): \(jsonFiles.joined(separator: ", "))")

    // Validate JSON files
    var allValid = true
    for file in jsonFiles {
        let path = "\(inputDir)/\(file).json"
        if !validateJSON(at: path, modelName: modelName) {
            allValid = false
        }
    }

    if !allValid {
        print("Warning: Some JSON files may have issues")
    }

    // Determine stubs subdirectory
    // e.g., "Tests/Stubs/AdBidding" -> "Stubs/AdBidding"
    let stubsSubdirectory: String
    if inputDir.contains("Tests/") {
        stubsSubdirectory = String(inputDir.split(separator: "/", maxSplits: 1).last ?? "")
    } else {
        stubsSubdirectory = "Stubs/\(moduleName)"
    }

    // Generate code
    let config = GeneratorConfig(
        moduleName: moduleName,
        modelName: modelName,
        inputDirectory: inputDir,
        outputDirectory: outputDir,
        stubsSubdirectory: stubsSubdirectory
    )

    let code = generateStubFactory(config: config, jsonFiles: jsonFiles)

    // Write file
    let outputPath = "\(outputDir)/\(moduleName)StubFactory.swift"
    writeFile(content: code, to: outputPath)

    print("Done!")
}

main()
