#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_SPEC="$ROOT_DIR/MSPDemoApp/project.yml"
WORKSPACE_SPEC="$ROOT_DIR/workspace.yml"
SWIFTPM_DIR="$ROOT_DIR/msp-ios-sdk.xcworkspace/xcshareddata/swiftpm"
SWIFTPM_JSON="$SWIFTPM_DIR/local-packages.json"
LOG_PREFIX="[update-workspace]"

mkdir -p "$SWIFTPM_DIR"

# List every Package.swift while ignoring build artifacts and Pods.
PACKAGE_FILES=()
while IFS= read -r pkg_file; do
  PACKAGE_FILES+=("$pkg_file")
done < <(find "$ROOT_DIR" -name Package.swift \
  ! -path '*/Pods/*' ! -path '*/DerivedData/*' ! -path '*/.build/*' \
  -print | LC_ALL=C sort)

if [[ ${#PACKAGE_FILES[@]} -eq 0 ]]; then
  echo "$LOG_PREFIX No Package.swift files found" >&2
fi

PACKAGE_NAMES=()
PACKAGE_REL_PATHS=()
for pkg in "${PACKAGE_FILES[@]}"; do
  pkg_dir="${pkg%/Package.swift}"
  pkg_name="$(basename "$pkg_dir")"
  rel_path="${pkg_dir#$ROOT_DIR/}"
  PACKAGE_NAMES+=("$pkg_name")
  PACKAGE_REL_PATHS+=("$rel_path")
done

# Write SwiftPM package manifest json for tooling/CI.
{
  echo "["
  for ((i=0; i<${#PACKAGE_NAMES[@]}; i++)); do
    name="${PACKAGE_NAMES[$i]}"
    rel="${PACKAGE_REL_PATHS[$i]}"
    suffix=",";
    if [[ $i -eq $((${#PACKAGE_NAMES[@]} - 1)) ]]; then
      suffix=""
    fi
    printf '  {"name":"%s","path":"%s"}%s\n' "$name" "$rel" "$suffix"
  done
  echo "]"
} > "$SWIFTPM_JSON"

declare -a SPM_APP_PRODUCTS=(
  "MSPCore"
  "NovaAdapter"
  "PrebidAdapter"
  "MSPGoogleAdapter"
  "MSPFacebookAdapter"
  "MSPSharedLibraries"
  "MSPOMSDK"
  "MSPiOSCore"
  "NovaCore"
)

# Helper to check if a package exists.
package_exists() {
  local name="$1"
  for candidate in "${PACKAGE_NAMES[@]}"; do
    if [[ "$candidate" == "$name" ]]; then
      return 0
    fi
  done
  return 1
}

# Generate the XcodeGen project spec for MSPDemoApp.
cat > "$PROJECT_SPEC" <<'YAML'
# This file is auto-generated by Scripts/update-workspace.sh
name: MSPDemoApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "15.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    DEVELOPMENT_TEAM: 4PEHUZX8QH
    PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoApp
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.0.117
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    INFOPLIST_FILE: MSPDemoApp/Info.plist
YAML

if [[ ${#PACKAGE_NAMES[@]} -eq 0 ]]; then
  echo "packages: {}" >> "$PROJECT_SPEC"
else
  echo "packages:" >> "$PROJECT_SPEC"
  for ((i=0; i<${#PACKAGE_NAMES[@]}; i++)); do
    name="${PACKAGE_NAMES[$i]}"
    rel="../${PACKAGE_REL_PATHS[$i]}"
    cat >> "$PROJECT_SPEC" <<YAML
  ${name}:
    path: ${rel}
YAML
  done
fi

cat >> "$PROJECT_SPEC" <<'YAML'
targetTemplates:
  BaseAppTarget:
    type: application
    platform: iOS
    sources:
      - path: MSPDemoApp
    info:
      path: MSPDemoApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
targets:
  MSPDemoApp:
    templates:
      - BaseAppTarget
    configFiles:
      Debug: ../Pods/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp.debug.xcconfig
      Release: ../Pods/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp.release.xcconfig
    prebuildScripts:
      - name: "[CP] Check Pods Manifest.lock"
        script: |
          if [ -z "${PODS_PODFILE_DIR_PATH}" ] || [ -z "${PODS_ROOT}" ]; then
            echo "error: CocoaPods environment variables are not set." >&2
            exit 1
          fi
          if [ ! -e "${PODS_ROOT}/Manifest.lock" ] || [ ! -e "${PODS_PODFILE_DIR_PATH}/Podfile.lock" ]; then
            echo "error: Run 'pod install' to generate Pods/Manifest.lock." >&2
            exit 1
          fi
          if ! diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" >/dev/null; then
            echo "error: Podfile.lock and Manifest.lock are out of sync. Run 'pod install'." >&2
            exit 1
          fi
        shell: /bin/sh
    postbuildScripts:
      - name: "[CP] Embed Pods Frameworks"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-frameworks.sh\""
        inputFileLists:
          - "${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-frameworks-${CONFIGURATION}-input-files.xcfilelist"
        outputFileLists:
          - "${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-frameworks-${CONFIGURATION}-output-files.xcfilelist"
      - name: "[CP] Copy Pods Resources"
        script: "\"${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-resources.sh\""
        inputFileLists:
          - "${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-resources-${CONFIGURATION}-input-files.xcfilelist"
        outputFileLists:
          - "${PODS_ROOT}/Target Support Files/Pods-MSPDemoApp/Pods-MSPDemoApp-resources-${CONFIGURATION}-output-files.xcfilelist"
  MSPDemoApp-SPM:
    templates:
      - BaseAppTarget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: MSPDemoApp.MSPDemoAppSPM
    configFiles:
      Debug: ../Configs/MSPDemoApp-Debug-SPM.xcconfig
      Release: ../Configs/MSPDemoApp-Release-SPM.xcconfig
    dependencies:
YAML

for product in "${SPM_APP_PRODUCTS[@]}"; do
  if package_exists "$product"; then
    cat >> "$PROJECT_SPEC" <<YAML
      - package: ${product}
        product: ${product}
YAML
  else
    echo "$LOG_PREFIX Warning: Skipping unknown package '${product}'" >&2
  fi
done

cat >> "$PROJECT_SPEC" <<'YAML'
  MSPDemoAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MSPDemoAppTests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MSPDemoApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MSPDemoApp"
    dependencies:
      - target: MSPDemoApp
  MSPDemoAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MSPDemoAppUITests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - target: MSPDemoApp
schemes:
  MSPDemoApp:
    build:
      targets:
        MSPDemoApp: all
        MSPDemoAppTests: test
        MSPDemoAppUITests: test
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - target: MSPDemoAppTests
        - target: MSPDemoAppUITests
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  MSPDemoApp-SPM:
    build:
      targets:
        MSPDemoApp-SPM: all
    test:
      config: Debug
      targets: []
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
YAML

# Generate the workspace specification so xcodegen can rebuild the .xcworkspace.
PROJECTS=()
while IFS= read -r proj; do
  PROJECTS+=("$proj")
done < <(find "$ROOT_DIR" -name '*.xcodeproj' \
  ! -path '*/DerivedData/*' ! -path '*/Pods/Pods.xcodeproj/*' \
  -print | LC_ALL=C sort)

pods_detected=0
{
  echo "workspace:"
  echo "  name: msp-ios-sdk"
  echo "  projects:"
  echo "    - MSPDemoApp/project.yml"
  for proj in "${PROJECTS[@]}"; do
    rel="${proj#$ROOT_DIR/}"
    # Skip the generated MSPDemoApp project - it will be created from the spec above.
    if [[ "$rel" == "MSPDemoApp/MSPDemoApp.xcodeproj" ]]; then
      continue
    fi
    if [[ "$rel" == "Pods/Pods.xcodeproj" ]]; then
      pods_detected=1
    fi
    project_name="$(basename "${rel%.*}")"
    echo "    - name: ${project_name}"
    echo "      path: ${rel}"
    echo "      type: file"
  done
  # Include Pods project if it exists.
  if [[ $pods_detected -eq 0 ]]; then
    echo "    - path: Pods/Pods.xcodeproj"
    echo "      type: file"
  fi
} > "$WORKSPACE_SPEC"

XCODEGEN_BIN="$(command -v xcodegen || true)"
if [[ -z "$XCODEGEN_BIN" ]]; then
  echo "$LOG_PREFIX xcodegen is not installed. Install via 'brew install xcodegen' (2.38.0+ required) and re-run this script." >&2
else
  echo "$LOG_PREFIX Running xcodegen generate"
  if ! "$XCODEGEN_BIN" generate --spec "$WORKSPACE_SPEC"; then
    echo "$LOG_PREFIX xcodegen failed. Ensure version 2.38.0+ is installed (run 'brew upgrade xcodegen')." >&2
  fi
fi

if [[ -f "$ROOT_DIR/Gemfile" ]]; then
  if [[ -n "${CI:-}" ]]; then
    echo "$LOG_PREFIX Running bundle exec pod install"
    if ! (cd "$ROOT_DIR" && bundle exec pod install); then
      echo "$LOG_PREFIX bundle exec pod install failed; please rerun locally." >&2
    fi
  else
    echo "$LOG_PREFIX Skipping pod install (run 'bundle exec pod install' locally to update Pods)."
  fi
fi

echo "$LOG_PREFIX Workspace spec -> $WORKSPACE_SPEC"
echo "$LOG_PREFIX Project spec -> $PROJECT_SPEC"
echo "$LOG_PREFIX SwiftPM packages -> $SWIFTPM_JSON"
